### ISSUE TITLE
Video: AnalyzeLabels test is failing.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1002]
[This test](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/ff662994ce2224ce4838454fe5f5994f22e58a5d/video/api/Test/Tests.cs#L100) is failing. I've skipped it in #1001 but it should be fixed.

@SurferJeffAtGoogle Assigning to you since you wrote this sample and test.

**Comment by amanda-tarafa** [comment]
And also [TestObjectTracking](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/ff662994ce2224ce4838454fe5f5994f22e58a5d/video/api/Test/Tests.cs#L189)

**Comment by SurferJeffAtGoogle** [comment]
@amanda-tarafa  When did the test start failing?  The exception being thrown is:

Grpc.Core.RpcException : Status(StatusCode=InvalidArgument, Detail="Request contains an invalid argument.")

If a request that used to succeed starts failing with InvalidArgument, that's a breaking change in the API.

**Comment by amanda-tarafa** [comment]
I believe it might be a problem with the video that's being used. See similar in Java: GoogleCloudPlatform/java-docs-samples#2545

**Comment by amanda-tarafa** [comment]
I don't know, I'll check.

**Comment by amanda-tarafa** [comment]
Made obsolote by #1293
