### ISSUE TITLE
Dlp: TestTriggers test is failing on CI

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1006]
Test is failing with this error: 

> Error: Grpc.Core.RpcException : Status(StatusCode=InvalidArgument, Detail="Invalid built-in info type name "US_ZIP".")

I haven't been able to reproduce it on local. Skipping the test for now in #1001 

@ace-n assigning to you since you were the last to significantly modify this test.
Let me know if I can help.

**Comment by ace-n** [comment]
Hi Amanda,

I haven't worked on DLP for quite a long time.

You might want to ping @SurferJeffAtGoogle (`rennie@`, .NET DPE who's updated these in the past) or @realjordanna (`jchord@`, DLP TL) to see if they can help.

Thanks!

**Comment by amanda-tarafa** [comment]
Thanks Ace. I'll look for a more suitable person to assing this to.

**Comment by amanda-tarafa** [comment]
Closed via #1082
