### ISSUE TITLE
Spanner: TestDataTypes timing out on CI

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1007]
After 10 minutes. (Locally it passes after around 2 minutes.)
I've skipped it in #1001 but it should be looked at.
One thing would be to separate out in single tests. At least we could isolate the culprit easier.

@skuruppu feel free to assign to someone from your team that can take care of it.

**Comment by skuruppu** [comment]
I hadn't noticed this flakiness since it seems to run fine locally. I didn't mange to dig into this today but I will take a look early next week.

**Comment by amanda-tarafa** [comment]
Yes, no rush, when you can. Admittely I've been noticing more timeouts than usual this past couple of weeks, not just Spanner, but other APIs as well.

**Comment by skuruppu** [comment]
Yikes, it's been almost a week and I still haven't had a chance to get to this. @laljikanjareeya would you please be able to take a look at this test? Thanks so much.

**Comment by amanda-tarafa** [comment]
Thanks both.
@laljikanjareeya I wasn't able to reproduce locally. I think that separating out into single tests might help with finding out where it's really timing out.
