### ISSUE TITLE
Cannot build speech example

### ISSUE THREAD

**Issue by SimonKravis** [GoogleCloudPlatform/dotnet-docs-samples#1011]
Trying to build speech example using Visual Studio 2019  on Win 10 I get errors

SpeechClient.StreamingRecognizeStream' does not contain a definition for 'ResponseStream' in many places in Recognize.cs and InfiniteStreaming.cs 

eg

 private SpeechClient.StreamingRecognizeStream _rpcStream;

 var response = _rpcStream.ResponseStream.Current;
                _serverResponseAvailableTask = _rpcStream.ResponseStream.MoveNext();

No overload  of Create takes 1 arguments in

  var speech = SpeechClient.Create(channel); in Recognize.cs

string' does not contain a definition for 'Host' and no accessible extension method 'Host' accepting a first argument of type 'string' could be found
in

var channel = new Grpc.Core.Channel(SpeechClient.DefaultEndpoint.Host,
                googleCredential.ToChannelCredentials());

I am referencing Google.Cloud.Speech.V1 (2.0.0)

**Comment by jskeet** [comment]
We're in the middle of fixing up all the samples for latest dependencies. See [this commit](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1001/commits/33f4d29c98e9aa1bca3c969fdfba7c6ede10ab8a) for the changes to the Speech samples.

Alternativel, you could use the older version of Google.Cloud.Speech.V1 (version 1.3.1) and the older sample will work.

**Comment by jskeet** [comment]
(Closing as I believe these two options should completely address your issue.)
