### ISSUE TITLE
Cloud Speech-to-Text: Diarization doesn't work in C#

### ISSUE THREAD

**Issue by welbertwpg** [GoogleCloudPlatform/dotnet-docs-samples#1034]
Hi,
I've been tried to do Diarization with the C# lib, and I always get 0 for the SpeakerTag field.

````csharp
            var speech = SpeechClient.Create();
            var operation = speech.LongRunningRecognize(new RecognitionConfig()
            {
                SampleRateHertz = 8000,
                LanguageCode = LanguageCodes.Portuguese.Brazil,
                EnableAutomaticPunctuation = true,
                Model = "default",
                DiarizationConfig = new SpeakerDiarizationConfig
                {
                    EnableSpeakerDiarization = true,
                    MaxSpeakerCount = 2,
                    MinSpeakerCount = 2
                }
            }, RecognitionAudio.FromStorageUri("gs://some-audio.wav"));
````
I used a .wav mono file
Am I doing something wrong? Or is it really not working?

**Comment by amanda-tarafa** [comment]
The `LongRunningRecognize` operation is a long running operation, which mean that what you are doing is just starting the operation, but you won't get all results expected until the operation has finished.
Add the following line of code after the snippet you pasted above and the check for the expected results.

`operation = operation.PollUntilCompleted().ThrowOnAnyError();`

**Comment by welbertwpg** [comment]
I was doing the `PollUntilCompleted` before, and I get the transcription result. I just don't get the SpeakerTag information.

**Comment by amanda-tarafa** [comment]
A few more questions: 

- Does this happen only with one audio file or with several files you have tried?
- According to do the Speech API docs, [here](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#recognitionconfig) and [here](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#wordinfo), for non streaming requests the `speaker_tag` field is only set for the top alternative in the final result. Are you not seing the tag there?
- Have you tried with loosening the restriction on the speaker count, leave it unset for instance?

If none of these questions help you diagnose this issue, it would be great if you could send an audio file and a full code snippet with which we could reproduce. And just to set time expectations, I probably won't be able to look at it today.

**Comment by welbertwpg** [comment]
> Does this happen only with one audio file or with several files you have tried?

I've tried with 5 different files.

> Have you tried with loosening the restriction on the speaker count, leave it unset for instance?

Yes, I tried this.

> According to do the Speech API docs, here and here, for non streaming requests the speaker_tag field is only set for the top alternative in the final result. Are you not seing the tag there?

I didn't see that, so it's impossible to get the information about all alternatives, and I was looking for the ones that didn't have the SpeakerTag information. This was the problem.

So, thank you for the help! :)
