### ISSUE TITLE
Add eventsforcloudrun samples

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/dotnet-docs-samples#1051]
Hi @meteatamel,
We're starting to move our samples to language repos.

Can you make a PR to move to code here:
https://github.com/gcpevents/eventsforcloudrun/pull/1

Into a new folder `run/events`:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/run

**Comment by meteatamel** [comment]
Sent a PR: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1053

**Comment by meteatamel** [comment]
Assigning to @grant to merge or assign to someone else who can merge

**Comment by grant** [comment]
Asked Jon for a review.

**Comment by amanda-tarafa** [comment]
@meteatamel This has been merged, right? Can we closed the issue?

**Comment by grant** [comment]
Thanks Mete!
