### ISSUE TITLE
[Spanner] Deactivate the QuickStart test, it keeps failing on Windows.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1062]
I've deactivated it in #1061 .
I've also added the JUnit logger dependency to the tests so that we can get more info.
So, I didn't need to add JUnit logger, it was already added, still we don't get good diagnostics info when the tests fail, might be because of the command runner.

**Comment by skuruppu** [comment]
Thanks for doing #1061 @amanda-tarafa. I'm not sure why the QuickStart started to fail.

@laljikanjareeya can I please ask you to take a look at debugging this?

**Comment by amanda-tarafa** [comment]
@skuruppu @laljikanjareeya , has this already been addressed as part of the samples that have been rewritten? Just checking in case we can close the issue.

**Comment by laljikanjareeya** [comment]
> @skuruppu @laljikanjareeya , has this already been addressed as part of the samples that have been rewritten? Just checking in case we can close the issue.

QuickStart sample is pending to add based on our new  convention(will be done into Part 4).
