### ISSUE TITLE
[Spanner] Deactivate Backup tests

### ISSUE THREAD

**Issue by skuruppu** [GoogleCloudPlatform/dotnet-docs-samples#1065]
The test times out so we're skipping this for now ([example](https://source.cloud.google.com/results/invocations/f255d775-e3ca-4231-b34d-8b70b669a0d7/targets/github%2Fdotnet-docs-samples%2Fspanner%2Fapi%2FSpannerTest/tests)). We should look into this and re-enable when we figure it out.

**Comment by skuruppu** [comment]
Test will be skipped in #1047.

**Comment by amanda-tarafa** [comment]
Thanks! Assigned to you but mostly so you can reassign. When I'm done with all the rest, if this is still around I will grab it.

**Comment by laljikanjareeya** [comment]
And `TestQueryWithBytes` is also failing . I've skipped it also.

**Comment by skuruppu** [comment]
`GoogleCloudSamples.Spanner.SpannerTests.TestUpdateBackup` timed out in this [run](https://source.cloud.google.com/results/invocations/ca33fcee-ddc2-48cd-88a5-a6859f3ef242/targets/github%2Fdotnet-docs-samples%2Fspanner%2Fapi%2FSpannerTest/tests). I think we're going to have to skip pretty much all the backups tests. I'm hoping to look into this tomorrow.

**Comment by amanda-tarafa** [comment]
Yep, on nightly CI running, Spanner is still timing out from time to time. I'm fine with deactivating the problematic tests. On rewrite we can address whatever is making them fail I think.

**Comment by amanda-tarafa** [comment]
@skuruppu , @laljikanjareeya Can't remember if this issue is still relevant. Ain't the backups being done just once now after the rewrite of some of the samples? It's fine if there's still some looese ends related to this, we can keep open until everything is addressed.

**Comment by laljikanjareeya** [comment]
> @skuruppu , @laljikanjareeya Can't remember if this issue is still relevant. Ain't the backups being done just once now after the rewrite of some of the samples? It's fine if there's still some looese ends related to this, we can keep open until everything is addressed.

We are not deleting backup every time test runs, This will not be an issue but still backup sample is pending to add(will add in part 4) so let keep this open for while.
