### ISSUE TITLE
Pub/Sub: audit samples

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/dotnet-docs-samples#1073]
Splitting #1050. @amanda-tarafa @laljikanjareeya 

Requesting a few more missing samples for Cloud Pub/Sub:

### Subscriber: 
1. pubsub_subscriber_async_pull_custom_attributes: [examples](https://cloud.google.com/pubsub/docs/pull#pull-messages-with-custom-attributes)
1. pubsub_subscriber_error_listener: does C# have a listener method like [Java](https://cloud.google.com/pubsub/docs/pull#java_1)? This one is optional. I suspect we need to rewrite/remove our other language samples because they don't follow what the Java sample is really doing.
1. pubsub_subscriber_concurrency_control: does C# allow concurrency control ([examples](https://cloud.google.com/pubsub/docs/pull#concurrency_control))? 
1. pubsub_subscriber_sync_pull_with_lease_management ([Go/Python/Node.js samples](https://cloud.google.com/pubsub/docs/pull#synchronous_pull_with_lease_management)): show modify ack deadline method.

### Publisher:
1. pubsub_publish_custom_attributes: [examples](https://cloud.google.com/pubsub/docs/publisher#config)
1. pubsub_publisher_retry_settings: [examples](https://cloud.google.com/pubsub/docs/publisher#retry). 
1. pubsub_publisher_concurrency_control: [examples](https://cloud.google.com/pubsub/docs/publisher#concurrency)

### Admin:
1. Create a push subscription ([other language samples](https://cloud.google.com/pubsub/docs/admin#creating_subscriptions))
 `[START pubsub_create_push_subscription]`
 `[END pubsub_create_push_subscription]`
1. Update push configuration ([other language samples](https://cloud.google.com/pubsub/docs/admin#change_pull_push))
 `[START pubsub_update_push_configuration]`
 `[END pubsub_update_push_configuration]`
1. List subscriptions in a topic ([other language samples](https://cloud.google.com/pubsub/docs/admin#listing_subscriptions))
 `[START pubsub_list_topic_subscriptions]`
 `[END pubsub_list_topic_subscriptions]`

## Delete:
1. Unused region tag `[START pubsub_quickstart_create_topic]`.

---

Also in the comment https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1194#issuecomment-700338944

**Comment by amanda-tarafa** [comment]
@laljikanjareeya Assigned to you for after we have merged the other Pub/Sub PRs, and also depending on your availability. Ping me internally if you won't be able to get to this in the next month or so.
