### ISSUE TITLE
pub/sub: remove old samples once location update

### ISSUE THREAD

**Issue by laljikanjareeya** [GoogleCloudPlatform/dotnet-docs-samples#1104]
Remove old samples once location has been updated in this [PR](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1050)

**Comment by anguillanneuf** [comment]
@laljikanjareeya Old samples are safe to be removed now. Thanks!

**Comment by laljikanjareeya** [comment]
@anguillanneuf Thank for the update!!
