### ISSUE TITLE
Events for Cloud Run for Anthos – GCS and PubSub tutorial

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/dotnet-docs-samples#1115]
Port the Events for Cloud Run samples for Anthos

**Comment by jskeet** [comment]
As a heads-up, when I've released the first drop of libraries for https://github.com/googleapis/google-cloudevents-dotnet, we might want to start using that for the tutorials.

**Comment by meteatamel** [comment]
Nice. We can definitely start using once it's out.

**Comment by jskeet** [comment]
I'm hoping it'll be within the next couple of hours :)
