### ISSUE TITLE
Secret version

### ISSUE THREAD

**Issue by ALMLAMBO** [GoogleCloudPlatform/dotnet-docs-samples#1126]
Hi,
I want to ask how can I create a secret version programmatically using C#?

**Comment by jskeet** [comment]
I'm afraid you'll need to be more specific. What exactly do you mean by "a secret version"?

**Comment by jskeet** [comment]
Also note that if you're not asking a question related to a specific *sample*, it would better to ask on the repository where the library you're using is based. For example, if this is a question about a `Google.Cloud.Xyz` library, please use https://github.com/googleapis/google-cloud-dotnet

**Comment by amanda-tarafa** [comment]
@ALMLAMBO I'll be closing this issue now since we need more information from you to be able to help you. Do add a comment with the information requested by @jskeet and we can reopen.
