### ISSUE TITLE
Spanner: samples should follow the samples guide 

### ISSUE THREAD

**Issue by laljikanjareeya** [GoogleCloudPlatform/dotnet-docs-samples#1136]
All the sample should follow the samples guide, this will also remove the command line argument.

**Comment by skuruppu** [comment]
@laljikanjareeya thanks for all your work on the samples. What are your next steps?

**Comment by laljikanjareeya** [comment]
> @laljikanjareeya thanks for all your work on the samples. What are your next steps?

@skuruppu still few samples are pending one more PR to come.

**Comment by amanda-tarafa** [comment]
> @laljikanjareeya thanks for all your work on the samples. What are your next steps?

+1 @laljikanjareeya, and on the repo in general, thanks!!!
