### ISSUE TITLE
Asset: BatchGetAssetsHistoryTest which fails on Windows.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1141]
@yuyifan-google In #1140 I've fixed an error that we had on the script that executes tests and that was printing RemoteException for the Asset test failure.
Now we can see the [real failure](https://source.cloud.google.com/results/invocations/fdd550af-917d-4692-be1a-486d5e4c0680/targets/github%2Fdotnet-docs-samples%2Fasset%2Fapi%2FAsset.Samples.Tests%2FTestResults/tests): Error: Grpc.Core.RpcException : Status(StatusCode=InvalidArgument, Detail="Request contains an invalid argument.")
It definitely seems to be a problem with the sample. And it seems to only happen on windows.
Can you please take a look? You can wait till I've merged #1140 so you get the fixed test running script.

**Comment by peter-zheng-g** [comment]
Is this issue still there?

**Comment by amanda-tarafa** [comment]
This continued to be flaky, but I've figured out why. For `startTime` we were sending `DateTime.UtcNow`, but if the backend clock is a little late, we get this `Invalid Argument` error. In #1469, second commit, I've modified the sample and test so that we can send a `startTime` 5 minutes on the past.

**Comment by peter-zheng-g** [comment]
Awesome! Thanks for the fix.
