### ISSUE TITLE
Upload object stupid implementation

### ISSUE THREAD

**Issue by CalinBunea** [GoogleCloudPlatform/dotnet-docs-samples#1152]
Hello,
Sorry about the title but I'm really pissed off. I would expect from a company like Google to have smart, open minded people working on their API with smart product managers.
In a context of Storage API functionality, how did you guys thought to offer a method which uploads a blob by using a Stream as input? Did you assumed that people will always upload a blob from local disk files or what? 
In BigData environment, every extra processing costs time and money. I have a use case where I read data from a storage in a streamable way, I apply some transformation on it and I want to write it in google blob in a streamable way as well. But if google API forces me to supply a stream as parameter for upload, what shall I do? Storing all my data in a memory stream is out of question since we are talking about GB of data. Should I store it on disk just to be then read back by google API?

Of course none of the above options aren't suitable so I ended up by creating a FIFO stream with an inner ring buffer (thanks for that btw) which is not a trivial work... (maybe I will provide the code here so other people having same use case can use it).

I've worked with similar APIs and I haven't seen this approach ever! You should provide the opened network stream on which I can write. When I dispose that stream, it means I'm done with the data writing and behind the scene, you should flush all the content and do whatever additional processing you want (i.e. some sort of commit) in order to mark the blob as completed. 
And please don't come with argument that you thought about resumable option because that can be achieved in other ways as well.
Thank you for reading this.

**Comment by CalinBunea** [comment]
Added a link to a quick implementation I did for a FIFOStream with ring buffer. 
[https://drive.google.com/file/d/1XZauvmmfyR3JdY15XBvDdbDDoTGubvvl/view](url)

**Comment by JustinBeckwith** [comment]
Greetings @CalinBunea - sorry to hear you're having trouble.   I went ahead and cleaned up some of the less-than-awesome language in the original issue.  In the future - please try to remember that we're all humans on the other side of the GitHub void here :) If you have any questions, I'll refer you to our code of conduct:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/CODE_OF_CONDUCT.md
