### ISSUE TITLE
run/events: Use Unmarshal Types Rather Than dynamic

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/dotnet-docs-samples#1156]
## Actual

Currently in our run/events samples, we don't use types for "unmarshaling" our JSON payload:

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/run

i.e.

```cs
dynamic cloudEventData = JsonConvert.DeserializeObject(body);
```

## Expected

We should use our type library to not have dynamic types. Not sure exactly how it would look in .NET

```cs
MessagePublishedData cloudEventData = ???(body);
```

Type Library:

https://github.com/googleapis/google-cloudevents-dotnet/tree/master/src/Google.Events.Protobuf/Cloud/PubSub/V1

---

I'm not very familiar with .NET. @jskeet can provide more information on the types for .NET.

**Comment by jskeet** [comment]
The first thing would be to use the CloudEvents SDK to convert the HttpRequestMessage to a CloudEvent, then use 

```csharp
var data = CloudEventConverters.ConvertCloudEventData<MessagePublishedData>(cloudEvent);
```

**Comment by meteatamel** [comment]
Note that my PR only makes PubSub sample to use the strong event type. The Storage sample only reads CloudEvent headers and I think we want to keep it that way, so it can be used both in Managed and Anthos versions of eventing.
