### ISSUE TITLE
[Spanner]: Consider using the creation_date field for detecting stale databases in tests.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1174]
See thread in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1138#discussion_r484849022

**Comment by anshuldavid13** [comment]
This change is now redundant as the code has been overwritten and the logic changed for deleting databases now.
Refer #1794 for updated code changes
