### ISSUE TITLE
![1](https://user-images.githubusercontent.com/26163841/92417897-65362d00-f16d-11ea-8a6f-1a8963c21599.jpg)

### ISSUE THREAD

**Issue by yesman236** [GoogleCloudPlatform/dotnet-docs-samples#1177]
![1](https://user-images.githubusercontent.com/26163841/92417897-65362d00-f16d-11ea-8a6f-1a8963c21599.jpg)

__Originally posted by @Arhell in https://github.com/dotnet-foundation/website/issues/332__

**Comment by jskeet** [comment]
Closing and reporting user for spam (two spurious issues in one day).
