### ISSUE TITLE
FireStore - Collection group queries Support

### ISSUE THREAD

**Issue by mitulpanch** [GoogleCloudPlatform/dotnet-docs-samples#1183]
Collection group queries support is missing as it is available in other libraries
https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query

**Comment by mitulpanch** [comment]
https://github.com/googleapis/google-cloud-dotnet/issues/4907

this says it is already available for .net

**Comment by jskeet** [comment]
As you can see from that issue, the feature is already supported - use `FirestoreDb.CollectionGroup`. Yes, the *sample* is still missing, but there's an internal issue for that already - we don't need an issue in *this* repository.

(I've been writing Functions Framework samples recently, so I should be able to write this Firestore sample next week.)

**Comment by jskeet** [comment]
Reopening as it *is* an issue for this repo - that's the downside of trying to handle issues on a mobile over the weekend.

It turns out that when I added samples for the previous issue, I missed the last one. Hoping to get it done today.

**Comment by jskeet** [comment]
The sample is now merged, which is why this issue is fixed - but it won't show up in the public docs until we've made an internal change as well. So @mitulpanch please refer to the linked PR for now.

**Comment by jskeet** [comment]
The documentation is now published: https://firebase.google.com/docs/firestore/query-data/queries#c_12
