### ISSUE TITLE
Sample cloud-sql/mysql does not handle concurrent requests correctly

### ISSUE THREAD

**Issue by jpharaoh-google** [GoogleCloudPlatform/dotnet-docs-samples#1199]
It looks like a single database connection is registered as a singleton, which will then be shared by all threads.

Sample error messages:
- Connection timed out
- Unable to read data from the transport connection: Connection timed out.
- Reading from the stream has failed.
- Fatal error encountered attempting to read the resultset.
- Fatal error encountered during command execution.
- Object reference not set to an instance of an object.
- Connection must be valid and open.

**Comment by amanda-tarafa** [comment]
Not sure that samples are intended to be used/run in a concurrent manner.
@shubha-rajan @kurtisvg ?

**Comment by kurtisvg** [comment]
These samples should be abled to be used in a concurrent manner.

My assumption was that the "connection" was actually a pool, but checking out the [ADO.NET connection pooling documentation](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling) it doesn't look like this is actually the case. Instead, it looks like ADO.NET pools the connections implicitly when the object is created, as long as the connection string is the same. So these samples need to be updated to reflect proper usage. 

Assigning to @craiglabenz to take care of this.
