### ISSUE TITLE
[Product search]: passing maxresults parameter with C#

### ISSUE THREAD

**Issue by josephws** [GoogleCloudPlatform/dotnet-docs-samples#1241]
I cannot find the a way to pass the maxresults parameter in google vision api product search C# sample code.

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/vision/api/ProductSearch/ProductSearch.cs

Please advise.

**Comment by jskeet** [comment]
I don't believe we have a way of easily doing that via the convenience `DetectSimilarProducts` method - instead you'd have to call `Annotate`, passing in an `AnnotateImageRequest` with a `Feature` that specifies that you want product search, along with the max results etc.

Untested:

```csharp
var feature = new Feature
{
    Type = Feature.Types.Type.ProductSearch,
    MaxResults = 10
};
var context = new ImageContext
{
    ProductSearchParams = new ProductSearchParams { ... }
};
var request = new AnnotateImageRequest
{
    Image = image,
    ImageContext = context
    Features = { feature }
};
var response = client.Annotate(request);
var productResults = response.ProductSearchResults;
```

**Comment by amanda-tarafa** [comment]
Closing as a solution was proposed and we haven't received feedback.
