### ISSUE TITLE
Firestore reading array value

### ISSUE THREAD

**Issue by heeshala** [GoogleCloudPlatform/dotnet-docs-samples#1260]
How is it possible to read the array index value using C# code ?

I was able to get string data types using [FirestoreProperty] public string name{ get; set; }

but  [FirestoreProperty] public string[] arr{ get; set; }

do not work

**Comment by jskeet** [comment]
Please could you refile this in https://github.com/googleapis/google-cloud-dotnet? (I can't transfer between the different organizations, I'm afraid.)

I would *expect* this to work out of the box - when you file the new issue, please could you clarify what "do not work" means? Are you reading or writing data? Is an exception thrown?

(I'll close this issue now, in anticipation of the new one.)
