### ISSUE TITLE
Spanner: Tests faling with duplicate column name.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1271]
Affecting all Spanner tests since this is happening in the fixture: Error: Google.Cloud.Spanner.Data.SpannerException : Duplicate column name Albums.MarketingBudget.

See sample [CI output](https://source.cloud.google.com/results/invocations/00fb02fd-8e97-40af-b459-c95f324ef2dd/targets/github%2Fdotnet-docs-samples%2Fspanner%2Fapi%2FSpanner.Samples.Tests%2FTestResults/tests).

**Comment by skuruppu** [comment]
I think this was a flake. I haven't seen the same failure after this instance. For example in [this](https://fusion2.corp.google.com/invocations/8d0a78ba-07ea-4b0f-8bf4-8461bc73e3fd/targets/cloud-devrel%2Fdotnet-docs-samples%2Flinux%2Fpresubmit2;config=default/log) which ran after the CI test above.

In a normal run of the tests the output looks like this:
```
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
Data inserted.
Added the MarketingBudget column.
Added the AlbumsByAlbumTitle index.
Added the AlbumsByAlbumTitle2 index.
Database my-test-database already exists.
Backup my-test-database-backup already exists.
Added the Revenue column.
...
```

In this failed case, the output looks like:
```
Data inserted.
OperationStopped: FAILED with exit code 1
[xUnit.net 00:00:29.77]     AddNumericColumnTest.TestAddNumericColumn [FAIL]
[xUnit.net 00:00:29.78]     CreateBackupTest.TestCreateBackup [FAIL]
[xUnit.net 00:00:29.78]     CreateDatabaseAsyncTest.TestCreateDatabaseAsync [FAIL]
[xUnit.net 00:00:29.78]     CreateDatabaseWithRetentionPeriodAsyncTest.TestCreateDatabaseWithRetentionPeriodAsync [FAIL]
[xUnit.net 00:00:29.79]     CustomTimeoutsAndRetriesTest.CustomTimeoutsAndRetries [FAIL]
[xUnit.net 00:00:29.79]     DeleteUsingDmlCoreAsyncTest.TestDeleteUsingDmlCoreAsync [FAIL]
[xUnit.net 00:00:29.81]     DeleteUsingPartitionedDmlCoreAsyncTest.TestDeleteUsingPartitionedDmlCoreAsync [FAIL]
[xUnit.net 00:00:29.82]     InsertUsingDmlCoreAsyncTest.TestInsertUsingDmlCoreAsync [FAIL]
[xUnit.net 00:00:29.82]     LogCommitStatsAsyncTest.TestLogCommitStatsAsync [FAIL]
  X AddNumericColumnTest.TestAddNumericColumn [1ms]
  Error Message:
   Google.Cloud.Spanner.Data.SpannerException : Duplicate column name Albums.MarketingBudget.
  Stack Trace:
     at Google.Cloud.Spanner.Data.SpannerCommand.ExecutableCommand.ExecuteDdlAsync(CancellationToken cancellationToken)
   at Google.Cloud.Spanner.Data.SpannerCommand.ExecutableCommand.ExecuteDdlAsync(CancellationToken cancellationToken)
   at AddColumnAsyncSample.AddColumnAsync(String projectId, String instanceId, String databaseId) in /tmpfs/src/github/dotnet-docs-samples/spanner/api/Spanner.Samples/AddColumnAsync.cs:line 30
   at SpannerFixture.InitializeDatabaseAsync() in /tmpfs/src/github/dotnet-docs-samples/spanner/api/Spanner.Samples.Tests/SpannerFixture.cs:line 117
   at SpannerFixture.InitializeAsync() in /tmpfs/src/github/dotnet-docs-samples/spanner/api/Spanner.Samples.Tests/SpannerFixture.cs:line 48
  X CreateBackupTest.TestCreateBackup [1ms]
....
```

It's not very easy to tell what happened from the logs but I think a DML call probably timed out, so some retry mechanism kicked in and tried adding the column again, after which the database started returning an error.

According to the code, there's only [one time](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/search?q=AddColumnAsync) where `AddColumnAsync` could be called, assuming that we're not trying to run tests for both the old version of the the samples and the new ones.

**Comment by skuruppu** [comment]
I'm not sure that there is anything to fix here but @amanda-tarafa let me know your thoughts.

**Comment by amanda-tarafa** [comment]
Yep, it's a flake for sure, I think I saw it once before but no more than that. I also took a brief look and couldn't make out how it would happaned. I thought it might have been the tests running at the same time on Linux and Windows, but then the failure would have been on database creation, not here. And we are not running the old tests either.
Maybe catch that exception, check that the error code indicates a duplicate, and ignore it in that case? I'd like to understand it better, but I agree it's probably related to some retry that's being erronously reported by the backend.

**Comment by laljikanjareeya** [comment]
Definitely this seem like flaky and not able to reproduce it locally. I have loop it for 50 time to create database and add column but it's working fine.

Based on `SpannerFixture` I just copy the sample and created below program:

```C#
    class Program
    {
        static string ProjectId = "project-id";
        static string InstanceId = "instance-id";
        static void Main(string[] args)
        {
            for (int i = 0; i < 50; i++)
            {
                Console.WriteLine($"Start --> {i}");
                RunSamples().Wait();
                Console.WriteLine($"Finish --> {i}");
            }
        }

        static async Task RunSamples()
        {
            try
            {
                var databaseId = $"my-db-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}";
                CreateDatabaseAsyncSample createDatabaseAsyncSample = new CreateDatabaseAsyncSample();
                InsertDataAsyncSample insertDataAsyncSample = new InsertDataAsyncSample();
                InsertStructSampleDataAsyncSample insertStructSampleDataAsyncSample = new InsertStructSampleDataAsyncSample();
                AddColumnAsyncSample addColumnAsyncSample = new AddColumnAsyncSample();
                await createDatabaseAsyncSample.CreateDatabaseAsync(ProjectId, InstanceId, databaseId);
                await insertDataAsyncSample.InsertDataAsync(ProjectId, InstanceId, databaseId);
                await insertStructSampleDataAsyncSample.InsertStructSampleDataAsync(ProjectId, InstanceId, databaseId);
                await addColumnAsyncSample.AddColumnAsync(ProjectId, InstanceId, databaseId);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
```

**Comment by amanda-tarafa** [comment]
I'll close this one for now as not reproduceable. I'll reopen if I see it again.
