### ISSUE TITLE
Pub/Sub: add schema samples 

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/dotnet-docs-samples#1279]
Assigned to @kamalaboulhosn with internal tracking bugs. 
Please assign @amanda-tarafa for review.

- [x] create avro schema
- [x] create proto schema
- [x] get schema
- [x] list schemas
- [x] delete scheam
- [x] create topic with schema
- [x] publish avro records
- [x] publish proto messages
- [x] subscribe with avro schema
- [x] subscribe with proto schema

See [Java](https://github.com/googleapis/java-pubsub/pull/509) and [Python](https://github.com/googleapis/python-pubsub/pull/306) examples. 

See published schema [docs](https://cloud.google.com/pubsub/docs/schemas).

**Comment by amanda-tarafa** [comment]
@anguillanneuf Can you check whether this was fully addressed by #1322 . I think it was but you may know better. Thanks!

**Comment by anguillanneuf** [comment]
Yes, this was fixed by #1332 . Thanks @amanda-tarafa  for double-checking!
