### ISSUE TITLE
Logging to GKE fails to set container_name label

### ISSUE THREAD

**Issue by PaulMazzuca** [GoogleCloudPlatform/dotnet-docs-samples#1282]
I am finding that when I log in GKE using option 1 (https://cloud.google.com/logging/docs/integrate/dotnet) the resource.label.container_name field is empty.  This seems odd especially given that the pod_name, cluster_name and location are present. In other logging frameworks by Google such as the Python and Java one's the conatiner_name is set. This is causing issues with log analysis since we cannot properly query for a specific container. Is there a reason why this label is not set?

Below is a very small example of how I am adding the logger.
```
using Google.Cloud.Diagnostics.AspNetCore;
...
loggerFactory.AddGoogle(app.ApplicationServices, "project-name");

```

**Comment by amanda-tarafa** [comment]
Yes we know about this and we are tracking here https://github.com/googleapis/gax-dotnet/issues/432. I'll close this one now but feel free to follow the one I've linked. Thanks
