### ISSUE TITLE
Clouddemo: Failed to build, but only transiently.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1286]
See CI logs [here](https://source.cloud.google.com/results/invocations/73312485-45fb-41eb-b505-bd2bc8c09b77/targets/github%2Fdotnet-docs-samples%2Fapplications%2Fclouddemo%2Fnetcore/tests). Not much information there unfortunatelly.
Might be another manifestation of #1278 

@jpassing I understand this might be just a one-of. But it would be great if you could take a quick look.
I'm also creating the issue to be able to track this from the start. Even if we close it now as a one-of, we can always reopen later if it continues to happen. Thanks

**Comment by jpassing** [comment]
`FAILED with exit code 139` looks like a segfault -- have we changed CLR versions recently?

**Comment by amanda-tarafa** [comment]
No, we haven't made any changes to CI.
Also, it just failed once, yesterday, in one of the presubmits, but it's been fine on the rest of the presubmits and the nightly runs, so it's very probably just transient.
Mainly wanted to track it in case it happens again.
I'll be closing now as one-of and I'll reopen if I see it again.
Thanks
