### ISSUE TITLE
c# Speech to text samples

### ISSUE THREAD

**Issue by koderi-dp** [GoogleCloudPlatform/dotnet-docs-samples#1305]
Hi,

I see that all of c# speech to text samples are removed from here and from 
https://cloud.google.com/speech-to-text/docs/endless-streaming-tutorial

will there be new samples or this is end for C# support :)

Thanks

**Comment by amanda-tarafa** [comment]
FYI @telpirion for you to answer or forward to someone who can. Thanks.

**Comment by telpirion** [comment]
Hello @koderi-dp,

C# is still a supported language with a client library--see the [Google.Cloud.Speech package on Nuget](https://www.nuget.org/packages/Google.Cloud.Speech.V1/). Samples have been removed due to maintenance concerns.

**Comment by dp-code101** [comment]
Don't undrestand why are you closing this ticket, so we have package available but without any example how to use it, are you planing to have examples for c# or answer is "mainteance concerns"?

**Comment by telpirion** [comment]
The reference documentation is still available for the [package](http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Speech.V1/index.html), which should help you with usage. The [product documentation](https://cloud.google.com/speech-to-text/docs/) is also available.

**Comment by dp-code101** [comment]
This is product documentation
![6D1F9CC4-E59D-4E36-8D9F-FC8DE8A6E784](https://user-images.githubusercontent.com/81353820/114429612-dafbee80-9bbd-11eb-8bcb-061940d31dd1.png)

dont see c# there, for package documentation is 2 code blocks and hot to install package

**Comment by telpirion** [comment]
If your concern is with the product documentation, you should log an an issue there.

**Comment by koderi-dp** [comment]
@telpirion thanks, you were very helpful.

**Comment by morphx666** [comment]
> 
> 
> @telpirion thanks, you were very helpful.



> 
> 
> Hi,
> 
> I see that all of c# speech to text samples are removed from here and from
> https://cloud.google.com/speech-to-text/docs/endless-streaming-tutorial
> 
> will there be new samples or this is end for C# support :)
> 
> Thanks

You can always browse an older commit and get the samples from there.
