### ISSUE TITLE
<!-- probot comment [9602930]-->

### ISSUE THREAD

**Issue by MoneyMan573** [GoogleCloudPlatform/dotnet-docs-samples#1308]
Here is the summary of possible violations 😱<details>
  <summary>There is a possible violation for not having product prefix.</summary>

  - [quickstart/README/main.yml:16](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L16), tag `all`

</details>

**The end of the violation section. All the stuff below is FYI purposes only.**

---
Here is the summary of changes.
<details>
  <summary>You are about to add 11 region tags.</summary>

  - [quickstart/README/main.yml:16](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L16), tag `all`
- [quickstart/README/main.yml:97](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L97), tag `auth_cloud_implicit`
- [quickstart/README/main.yml:114](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L114), tag `auth_cloud_explicit`
- [quickstart/README/main.yml:133](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L133), tag `auth_cloud_explicit_compute_engine`
- [quickstart/README/main.yml:159](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L159), tag `auth_api_implicit`
- [quickstart/README/main.yml:187](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L187), tag `auth_api_explicit`
- [quickstart/README/main.yml:214](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L214), tag `auth_api_explicit_compute_engine`
- [quickstart/README/main.yml:247](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L247), tag `auth_http_implicit`
- [quickstart/README/main.yml:284](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L284), tag `auth_http_explicit`
- [quickstart/README/main.yml:333](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L333), tag `auth_cloud_explicit`
- [quickstart/README/main.yml:349](https://github.com/MoneyMan573/dotnet-docs-samples/blob/26fce79afc90e8917b7e1e5fd0178da4dc9a772e/quickstart/README/main.yml#L349), tag  `auth_cloud_explicit_compute_engine`

</details>

---
This comment is generated by [snippet-bot](https://github.com/apps/snippet-bot).
If you find problems with this result, please file an issue at:
https://github.com/googleapis/repo-automation-bots/issues.
To update this comment, add `snippet-bot:force-run` label or use the checkbox below:
- [x] Refresh this comment

_Originally posted by @snippet-bot[bot] in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1307#issuecomment-817186914_

**Comment by amanda-tarafa** [comment]
Closing as the PR that produced this has been closed as spam.
