### ISSUE TITLE
Spanner: CreateInstanceTest is flaky

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1332]
```
[xUnit.net 00:04:01.76]     CreateInstanceTest.TestCreateInstance [FAIL]
Waiting for the operation to finish.
  X CreateInstanceTest.TestCreateInstance [8ms]
  Error Message:
   Assert.Equal() Failure
Expected: AlreadyExists
Actual:   Unavailable
  Stack Trace:
     at CreateInstanceTest.TestCreateInstance() in /tmpfs/src/github/dotnet-docs-samples/spanner/api/Spanner.Samples.Tests/CreateInstanceTest.cs:line 34
```

**Comment by skuruppu** [comment]
@laljikanjareeya if you could take a look, that would be great. I wonder if we just need to put this in a retry loop.

**Comment by laljikanjareeya** [comment]
> I wonder if we just need to put this in a retry loop.

Do you want to put a custom retry setting in the create instance sample?

**Comment by skuruppu** [comment]
No, not quite, I was hoping we can do so in the test. Would that be possible?

**Comment by laljikanjareeya** [comment]
we can not do it in test because we are pulling operation until completed(`PollUntilCompleted()`) in sample.

**Comment by zoercai** [comment]
🚨 friendly triager ping @skuruppu @laljikanjareeya

**Comment by olavloite** [comment]
> we can not do it in test because we are pulling operation until completed(`PollUntilCompleted()`) in sample.

@laljikanjareeya I think we can safely retry the entire test call in the test method itself, without having to change the sample. See #1337
