### ISSUE TITLE
Google Home Demo: Modernize application and update dependencies.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1427]
This sample code seems to be somewhat outdated. Code changes are needed to bring it up to date. But that just makes sense if this samples is still relevant which I don't have the context to know.

@meteatamel , what do you think? Look at the renovate PRs that I'm closing pointing to this issue for the dependencies that need updating. Thanks!

**Comment by meteatamel** [comment]
@amanda-tarafa AFAIK, I don't think this sample is being used from any docs or anywhere else. I don't have plans to keep it up to date. My suggestion is to either keep the sample as is, without any library updates.

**Comment by amanda-tarafa** [comment]
OK, I'll think about it. Specially if they are not being referenced by any docs, I'm more inclined to delete it. We can always bring it back to live if we decide we want to include it somewhere.

**Comment by amanda-tarafa** [comment]
Closed by #2248
