### ISSUE TITLE
Text to speech sample

### ISSUE THREAD

**Issue by PetrMahdalicek** [GoogleCloudPlatform/dotnet-docs-samples#146]
Hi, 
do you plan to create sample project for .net showing text to speech api usage?
I checked it, but I didn't understand how to use it.

Petr

**Comment by SurferJeffAtGoogle** [comment]
Google presently does not offer a text-to-speech API.  Are you referring to the speech-to-text API?
https://cloud.google.com/speech/

**Comment by PetrMahdalicek** [comment]
Sorry, by bad. But, if you hade this api, I would use it :-)

Thank you

**Comment by SurferJeffAtGoogle** [comment]
Thanks Petr.  That's useful feedback.

**Comment by Fever905** [comment]
Would be nice if you were not the #1 result for "text to speech" .. would have saved me 20 minutes of looking for it in your cloud API.

**Comment by sebr74** [comment]
We all know you can do this Google. Your speech synthesis ( as used in maps for example ) is by far the best synthesizer out there. Thanks for sharing the Wavenet algorithm with the world, but only you have the data and ressources to train it properly. Why not make money and expose this marvel through an API?
