### ISSUE TITLE
Add samples for turbo replication (15 minute RPO)

### ISSUE THREAD

**Issue by ddelgrosso1** [GoogleCloudPlatform/dotnet-docs-samples#1509]
Samples need to be added for turbo replication ([client library request](https://docs.google.com/document/d/1ee3LzRfyArNIR4rLEeY60Eio7DBwLy5TkmvcMPxSork/edit?usp=sharing&resourcekey=0-4CYSH1Gc0ekxa1oUntE9yg)). 

Please see NodeJS example here: https://github.com/googleapis/nodejs-storage/pull/1618

Please wait for approval from myself before merging or releasing this change so we can coordinate around release dates.

**Comment by amanda-tarafa** [comment]
@shivgautam assigning to you so you can reassing appropiately.

I can take it if you don't have the bandwidth.

**Comment by shivgautam** [comment]
@amanda-tarafa I'll get it done. Just got the timelines from Denis. This should be doable.

**Comment by anshuldavid13** [comment]
Samples done and merged
