### ISSUE TITLE
Changing the dotnet sample HelloWorld to handle GRPC fails

### ISSUE THREAD

**Issue by vbod** [GoogleCloudPlatform/dotnet-docs-samples#1644]
I was trying to have a Kestrel GRPC server deployed on Google-Cloud Run as the documentation says it's [legit to do so](https://cloud.google.com/run/docs/triggering/grpc). I started from the `run/helloworld` standard HTTP/1.1 Kestrel web-app, which works fine. Mixing it with a standard Kestrel GRPC project fails. To reproduce:

1. Create a new GRPC server: `dotnet new grpc TestGrpc` (tested with .net5.0 and .net6.0);
2. Change the `Program.cs` to match Cloud Run expectations:
```CSharp
using Test.Services;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGrpc();

var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
var url = $"http://0.0.0.0:{port}";

var app = builder.Build();

// Configure the HTTP request pipeline.
app.MapGrpcService<GreeterService>();
app.MapGet("/", () => "Communication with gRPC endpoints must be made through a gRPC client. To learn how to create a client, visit: https://go.microsoft.com/fwlink/?linkid=2086909");

app.Run(url);
```
3. Use the very same `Dockerfile` as provided in this documentation;
4. Build the image and push it in Artifacts Registry;
5. Create a Cloud Run instance with that image: note that [Kestrel requires HTTP/2](https://docs.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-6.0&tabs=visual-studio-code#kestrel) so we need to set Cloud Run to end-to-end HTTP/2 (otherwise it fails with a `protocol error`);
6. Run a simple client (or [grpcurl](https://github.com/fullstorydev/grpcurl)) and you will get the error:
```
upstream connect error or disconnect/reset before headers. reset reason: remote reset
```
7. On the other hand, on the Cloud Run instance there's a unique log about that request with for instance (but it never reaches the actual implementation, I've tried logging pretty much everywhere it's just like if there was some kind of middle-ware before reaching the user implementation that would block everything):
```
POST 200 1.02 KB 41 ms grpcurl/v1.8.6 grpc-go/1.44.1-dev https://***/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
```

Maybe there is something obvious I am missing, but any help would be appreciated. (I also posted on [stackoverflow](https://stackoverflow.com/questions/71207574/grpc-on-google-cloud-run-upstream-connect-error-or-disconnect-reset-before-hea)). I am eager to contribute in any possible way, whether it be helping creating a doc on how to have a .NET GRPC server on Cloud Run, or even investigate further if need be.
___
Note that it used to work a few days/week ago as I had a fully operational instance running but I can't explain why it does not succeed anymore.

**Comment by amanda-tarafa** [comment]
@meteatamel Can you take a look? Thanks!

**Comment by vbod** [comment]
It looks like it's not particularly due to GRPC but really to HTTP/2 only. If I simply try to design a server handling HTTP/2, I reproduce the very same error as I have with GRPC.

1. Use with the following `Program.cs`:
```CSharp
var builder = WebApplication.CreateBuilder(args);
var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
var url = $"http://0.0.0.0:{port}";
var app = builder.Build();
app.MapGet("/", () => "Hey there!");
app.Run(url);
```
2. This most basic `csproj`:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
```
3. Enforce HTTP/2 in the server (I did it in `appsettings.json` but it could be done programmatically providing the same error):
```
{
  "AllowedHosts": "*",
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
}
```
4. Build with a dockerfile (same as the one in your doc example e.g.) and push to Artifacts Registry, then create a Cloud Run instance (I don't know if it helps but I'm doing it in `europe-west1`) and it fails with the same error:
```
upstream connect error or disconnect/reset before headers. reset reason: remote reset
```

Maybe again I missed something, but it looks like there's been a change on end-to-end HTTP/2 that kind of breaks the expected behavior (both with a regular HTTP/2 server and a GRPC server). Everything works perfectly fine though when deployed locally with the very same docker image.

**Comment by meteatamel** [comment]
@vbod When you say it was working before, was it working with the same .NET 6 Cloud Run sample? Or was it working with the previous .NET Core 3.1 Cloud Run sample?

**Comment by vbod** [comment]
@meteatamel It was working with a .NET 5 HTTP/2 Kestrel server. I think it stopped during the weekend - but can't be sure as it's a sandbox project so I'm not tracking it daily.

**Comment by cgleadall** [comment]
I have had (gRPC) services deployed to Google Cloud Run for almost a year. Something happened over the weekend that broke all 4 (environments ; Alpha, Dev, Test, Prod) of them. The revision images (for some of these environments) has not been touched for a few weeks.
One of the environments (Prod) has not been deployed (ie: a new gcloud revision) since January 18th 2022.

I don't think that this is a `dotnet` issue. Unless the base image image for my image has changed...
from my Dockerfile:
`FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base` 

@vbod does the sample you are working with run locally?
 - `dotnet run`
 -  `docker run`

**Comment by vbod** [comment]
@cgleadall Everything works perfectly fine locally for me with `dotnet run` or `docker run`. I really tend to think there must have been some kind of network change that impacted applications with end-to-end HTTP/2 (maybe with Envoy, I don't know what Cloud Run uses internally but I see a lot of similar errors with this project?). There are also more people impacted that published on stackoverflow for the same error that happened all of a sudden around this weekend, e.g. [here][https://stackoverflow.com/questions/71215192/unable-to-connect-to-basic-google-cloud-run-service-upstream-connect-error-or-d#71219829).

**Comment by amanda-tarafa** [comment]
These same issues are being reported on the [public issue tracker](https://issuetracker.google.com/savedsearches/5447537?pli=1). This is very unlikely related to the .NET sample but I'll keep this issue open till I've confirmed with the product team.

Please leave your comments to the issue tracker and follow the relevant issues there.

**Comment by amanda-tarafa** [comment]
Just as un update, I've reported this internally and it's being looked at. Do follow the issues in the issue tracker, but I'll also update here as soon as I know more.

**Comment by vbod** [comment]
I confirm that setting `AllowAlternateSchemes` to true fixes the bug and the server works as expected! Thanks a lot 🥳

**Comment by amanda-tarafa** [comment]
I have an update from the Cloud Run team.

The change that caused this breakage has been rolled back. The old behavior will be supported for the time being, and if/when it is deprecated, [Google Cloud deprecation policies](https://cloud.google.com/terms/deprecation) will be applied.

That said, setting [KestrelServerOptions.AllowAlternateSchemes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.allowalternateschemes?view=aspnetcore-6.0) to true shouldn't have any adverse effect on your running service, but do take care to follow the recommendations on the option documentation ([KestrelServerOptions.AllowAlternateSchemes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.allowalternateschemes?view=aspnetcore-6.0)).

Thanks for your patience.
