### ISSUE TITLE
google api speech recognition not working after 60 seconds

### ISSUE THREAD

**Issue by amitavak** [GoogleCloudPlatform/dotnet-docs-samples#172]
I am testing google api streamimg speech recognition.
I opened this project https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api/Recognize
and ran StreamingMicRecognizeAsync method from main. It was working fine.
But after 60 seconds or so it stopped recognizing audio from mic. I tried increasing the time in "ListenOptions.Seconds". It did not help.

did anyone face the same issue and find some workaround ?

Thanks.

**Comment by SurferJeffAtGoogle** [comment]
Streaming requests are limited to 60 seconds, as described here:
https://cloud.google.com/speech/limits
The only work-around I see is to issue multiple requests.
