### ISSUE TITLE
Credentials Issue

### ISSUE THREAD

**Issue by abethke** [GoogleCloudPlatform/dotnet-docs-samples#1729]
Good Day,

I am having problems authenticating with a Unity C# project published on to Android where the resulting error on device is:

`JsonSerializationException: Unable to find a constructor to use for type Google.Apis.Auth.OAuth2.JsonCredentialParameters. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'type', line 2, position 9.`

I am using a service agent credential json that is being successfully used in multiple other apps and works in this app in editor on Windows and OSX. The issue only occurs when trying to set the credentials path.

`Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", credentialsPath);`

Being that it is Unity on Android I am already aware that accessing the streamingAssets folder is not accessible and am using the workaround of writing the file locally to the Application.persistantDataPath. With that I have verified that the file does exist and a valid path is being set.

Having worked on this issue for quite some time now I would mention that I have also tried to stop code stripping using the link.xml file but that does not appear to be working unless my syntax is incorrect.

Here is the full link.xml I am using currently

<linker>
  
  <assembly fullname="UnityEngine">
    <type fullname="UnityEngine.Networking.UnityWebRequest" preserve="all" />
    <type fullname="UnityEngine.Networking.UploadHandlerRaw" preserve="all" />
    <type fullname="UnityEngine.Networking.UploadHandler" preserve="all" />
    <type fullname="UnityEngine.Networking.DownloadHandler" preserve="all" />
    <type fullname="UnityEngine.Networking.DownloadHandlerBuffer" preserve="all" />
  </assembly>
  <assembly fullname="mscorlib">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
  <assembly fullname="System">
    <namespace fullname="System.Security.Cryptography" preserve="all"/>
  </assembly>
  <assembly fullname="AWSSDK.Core" preserve="all"/>
  <assembly fullname="AWSSDK.CognitoIdentity" preserve="all"/>
  <assembly fullname="AWSSDK.SecurityToken" preserve="all"/>
  <assembly fullname="Newtonsoft.Json">
    
    <type fullname="System.Runtime.CompilerServices.NullableAttribute"/>
    <type fullname="System.Runtime.CompilerServices.NullableContextAttribute"/>

    
    
    <type fullname="Newtonsoft.Json.Converters.*Converter" preserve="all" />

    
    <type fullname="Newtonsoft.Json.Serialization.*NamingStrategy" preserve="all" />
  </assembly>
  <assembly fullname="Google.Apis.Auth.OAuth2">
    <type fullname="Google.Apis.Auth.OAuth2.JsonCredentialParameters" preserve="all" />
  </assembly>
  <assembly fullname="Google.Apis.Auth.OAuth2">
    <type fullname="Google.Apis.Auth.OAuth2.JsonCredentialParameters">
      <method signature="System.Void.ctor()"/>
    </type>
  </assembly>
</linker>

**Comment by amanda-tarafa** [comment]
Unfurtunately the Google.Apis.Auth library [does not support Unity](https://github.com/googleapis/google-api-dotnet-client/blob/main/FAQ.md#why-arent-unity-xamarin-or-uwp-supported) and won't do so for the time being.

I'm closing this issue now as there's not much we can do at the moment.
