### ISSUE TITLE
TreeView issue

### ISSUE THREAD

**Issue by mrsahin101** [GoogleCloudPlatform/dotnet-docs-samples#1778]
Hello. When I try to listen updates it get the updates. But when ever i try to add code related to treeview inside this Task ListenMultiple(string project) function it stops working. Couldn't figure out why.

**Comment by amanda-tarafa** [comment]
There are samples for many client libraries on this repo. From your question it is not possible to know which client library and which sample you are refering to.
The best way for us to help you is if you post a small but complete console application that reproduces the unexpected result you are seeing.

**Comment by mrsahin101** [comment]
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/04e97f8f218b39926d4d98f1bf9ab7bafb848be4/firestore/api/ListenData/Program.cs#L81-L92
i try to use this sample. It works normally but when i try to replace 90th line with this treeViewMachListNodes.Add(documentSnapshot.Id) it stops working. I don't know why but it could be related to something else.

**Comment by amanda-tarafa** [comment]
> It stops working

What does this means, the application crashes, you get an exception, the application continues to work but the result is different to what you expected.... ?
If you get an exception, please share the full stack trace.
If the result is unexpected, please share what result you are expecting and what is it that you are seeing.

> Then i call this functions in init function.

Init function of what?

Again, if you can share a simple but full console application that reproduces the problem we'll be able to help you faster.

**Comment by amanda-tarafa** [comment]
Note: If you can't reproduce the issue on a console application, but you reproduce it in a web app or another type of desktop app, it's fine, as long as the app you share is minimal (i.e. the minimum to reproduce the issue) and complete, we'll be able to help you way faster.

**Comment by mrsahin101** [comment]
```cs
   public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        FirestoreDb myLocalREf;
        private void Form1_Load(object sender, EventArgs e)
        {
            ListenMultiple().Wait();
        }
        private async Task ListenMultiple()
        {
            
            string path = @"mypathtojson";
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", path);

            myLocalREf = FirestoreDb.Create("myprojectname");

            CollectionReference citiesRef = myLocalREf.Collection("mycollection");
            Query query = myLocalREf.Collection("mycollection").WhereGreaterThan("mycondition", 0);

            FirestoreChangeListener listener = query.Listen(snapshot =>
            {
                /* Used when listbox code on */
                //listBox1.Items.Clear();

                foreach (DocumentSnapshot documentSnapshot in snapshot.Documents)
                {
                    if (documentSnapshot.Exists)
                    {
                        Dictionary<string, object> docKeyValPair = documentSnapshot.ToDictionary();
                        object myobject = docKeyValPair["myListofItems"];
                        MessageBox.Show("Event Occured");
                        IList myList = (IList)myobject;
                        
                        foreach (string key in myList)
                        {
                            /* This works*/
                            //listBox1.Items.Add(key);

                            /* Somehow this doesnt work.  */
                            treeView1.Nodes.Add(key);
                        }
                    }
                }
            });
        }
       /* here just to test out treeView1.Nodes.Add() works and it does work */
        private void button1_Click(object sender, EventArgs e)
        {
            for(int i = 0; i < 5; i++)
            {
                treeView1.Nodes.Add("Node" + i.ToString());
            }
        }
    }


I tried this on new project and still having same error. I added messagebox there to check whether If its getting the updates or not.  Whenever i add the treeview code there it doesnt work. But when i remove that and work with listbox it works without any problem. instantly gets the updates.
