### ISSUE TITLE
chore: snippet-bot full scan

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1874]
null

## snippet-bot scan result
Life is too short to manually check unmatched region tags.
Here is the result:
Great job! No unmatching region tags found!

---
Report generated by [snippet-bot](https://github.com/apps/snippet-bot).
If you find problems with this result, please file an issue at:
https://github.com/googleapis/repo-automation-bots/issues.

**Comment by amanda-tarafa** [comment]
@tmatsuo Not sure if this is supposed to be working? Or how can I check if the scan is running? Thanks!

**Comment by tmatsuo** [comment]
Yeah I saw some error logs. Let me debug.

**Comment by tmatsuo** [comment]
Fix is on a way:
https://github.com/googleapis/repo-automation-bots/pull/4252

**Comment by amanda-tarafa** [comment]
Oh thanks! that was super fast.

**Comment by tmatsuo** [comment]
"null" at the beginning is another bug, but it's working now.

**Comment by amanda-tarafa** [comment]
Closing as we are good. Thanks @tmatsuo for the quick fix.
