### ISSUE TITLE
FormatTopicName method does not exist.

### ISSUE THREAD

**Issue by Singh400** [GoogleCloudPlatform/dotnet-docs-samples#189]
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/quickstarts/pubsub/quickstart/QuickstartSample.cs#L34

https://cloud.google.com/pubsub/docs/reference/libraries

The method `FormatTopicName` does not exist in `PublisherClient`.

I am using this version:-

`<package id="Google.Cloud.PubSub.V1" version="1.0.0-beta07" targetFramework="net461" />`

**Comment by Singh400** [comment]
Example on docs should be updated to reflect the usage as seen [**here**](https://cloud.google.com/pubsub/docs/publisher#pubsub-create-topic-csharp).

**Comment by SurferJeffAtGoogle** [comment]
Thank you for reporting this issue.  See the new quickstart in the master branch.

**Comment by Singh400** [comment]
Hi @SurferJeffAtGoogle,

Do you know who I can get in touch with to update the example seen [**here**](https://cloud.google.com/pubsub/docs/reference/libraries)?

Thanks,
Singh
