### ISSUE TITLE
[Video Livestream and Stitcher]: Several quotas are being exceeded.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#1921]
ChannelCountPerProjectPerRegion in #1914 
InputCountPerProjectPerRegion in #1913
SlatesPerProjectPerRegion in #1910

There's resource cleanup but at the end of the test run only. It's possible that we'll need to delete resources at the end of each test that creates them.

Also, I've seen several "Service Unavailable" errors. If the frequency of these do not improve, we might need to add retries on the tests.

**Comment by irataxy** [comment]
These quotas have all been increased in the test project. 

I will implement retries as needed.
