### ISSUE TITLE
Google Speech To Text by Microfone 

### ISSUE THREAD

**Issue by ergunbilgehan** [GoogleCloudPlatform/dotnet-docs-samples#193]
I am working on Google Speech by c # . I want to use the microphone . My code is there But My code uses only audio files. Please help me . Thank you  

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Google.Cloud.Speech.V1Beta1;
namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            var speech = SpeechClient.Create();
            var response = speech.SyncRecognize(new RecognitionConfig()
            {
                LanguageCode = "tr-TR",
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRate = 16000,
            }, RecognitionAudio.FromFile("audio.wav"));
            foreach (var result in response.Results)
            {
                foreach (var alternative in result.Alternatives)
                {
                    Console.WriteLine(alternative.Transcript);
                   } }
 Console.ReadLine();
        }}}

**Comment by SurferJeffAtGoogle** [comment]
Have you tried to build and run this sample?
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api/Recognize

**Comment by ergunbilgehan** [comment]
Thank you for the help. Now  I need to I will convert this code to windows form.

**Comment by ergunbilgehan** [comment]
Thank you for your help! . I use this code . Thank you :)

2017-03-04 1:08 GMT+03:00 Jeffrey Rennie <notifications@github.com>:
