### ISSUE TITLE
Issue: audio data is being streamed too slow. please stream audio data approximately at real time

### ISSUE THREAD

**Issue by Anuradha2011** [GoogleCloudPlatform/dotnet-docs-samples#197]
I'm using below method to convert speech to text using microphone, and the sample rate is 16000. I have tested it on Windows 10 machine initially and it worked fine and later when I tested the same script on Windows 7 machine it is not working properly and I'm getting the below error message.

>  **audio data is being streamed too slow. please stream audio data approximately at real time**

How to decide which sample rate to beused on which machine? What could be the problem with my Windows 7 machine? 

// [START speech_streaming_mic_recognize]
        static async Task<object> StreamingMicRecognizeAsync(int seconds)
        {
           // code here....
          StreamingConfig = new StreamingRecognitionConfig()
                        {
                            Config = new RecognitionConfig()
                            {
                                Encoding =
                                RecognitionConfig.Types.AudioEncoding.Linear16,
                                SampleRate = 16000,
                            },
                            InterimResults = false,
                        }
          //  code here........
        }

Please help me in fixing this issue.

**Comment by SurferJeffAtGoogle** [comment]
I believe this has been fixed.  Please re-open if you see the bug again.
