### ISSUE TITLE
Build unsuccessful

### ISSUE THREAD

**Issue by robertandreibarbulescu** [GoogleCloudPlatform/dotnet-docs-samples#1979]
##[debug]   gcr.io/application-369421/clouddemo:31
##[debug]   /home/vsts/work/1/s/applications/clouddemo/netcore
/usr/bin/docker build -f /home/vsts/work/1/s/applications/clouddemo/netcore/Dockerfile --label com.azure.dev.image.system.teamfoundationcollectionuri=https://dev.azure.com/ContosoM365/ --label com.azure.dev.image.system.teamproject=CloudDemo --label com.azure.dev.image.build.repository.name=CloudDemo --label com.azure.dev.image.build.sourceversion=fdf22a0f7ab016bc4c1f1f5ad31421cf28e4f7fd --label com.azure.dev.image.build.repository.uri=https://ContosoM365@dev.azure.com/ContosoM365/CloudDemo/_git/CloudDemo --label com.azure.dev.image.build.sourcebranchname=bigquery --label com.azure.dev.image.build.definitionname=CloudDemo --label com.azure.dev.image.build.buildnumber=20221123.11 --label com.azure.dev.image.build.builduri=vstfs:///Build/Build/31 --label image.base.ref.name=mcr.microsoft.com/dotnet/aspnet:6.0 --label image.base.digest=sha256:503e677aba012b6a4516d054135669ee6074111da5ce1dd0e2847027b2c78a3b -t gcr.io/application-369421/clouddemo:31 /home/vsts/work/1/s/applications/clouddemo/netcore
Sending build context to Docker daemon   21.5kB

Step 1/17 : FROM mcr.microsoft.com/dotnet/aspnet:6.0
 ---> ab511e11221a
Step 2/17 : EXPOSE 8080
 ---> Running in ab9f4dc79da3
Removing intermediate container ab9f4dc79da3
 ---> 237edb1a58ba
Step 3/17 : WORKDIR /app
 ---> Running in a0a46ed56555
Removing intermediate container a0a46ed56555
 ---> 762702dd06a2
_Step 4/17 : COPY CloudDemo.MvcCore/bin/Release/net6.0/publish/ /app/
COPY failed: file not found in build context or excluded by .dockerignore: stat CloudDemo.MvcCore/bin/Release/net6.0/publish/:_ file does not exist
##[debug]Exit code 1 received from tool '/usr/bin/docker'
##[debug]STDIO streams have closed for tool '/usr/bin/docker'
##[error]COPY failed: file not found in build context or excluded by .dockerignore: stat CloudDemo.MvcCore/bin/Release/net6.0/publish/: file does not exist
##[debug]Processed: ##vso[task.issue type=error;]COPY failed: file not found in build context or excluded by .dockerignore: stat CloudDemo.MvcCore/bin/Release/net6.0/publish/: file does not exist
##[debug]task result: Failed
##[error]The process '/usr/bin/docker' failed with exit code 1
##[debug]Processed: ##vso[task.issue type=error;]The process '/usr/bin/docker' failed with exit code 1
##[debug]Processed: ##vso[task.complete result=Failed;]The process '/usr/bin/docker' failed with exit code 1
Finishing: Build and push image

**Comment by amanda-tarafa** [comment]
@jpassing can you take a look at this? Issue seems to be with CloudDemo.MvcCore. Thanks.

**Comment by amanda-tarafa** [comment]
Closed by #1981
