### ISSUE TITLE
[Video Stitcher]: Tests have been consistently failing for a couple of days

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#2100]
See logs [here](https://fusion2.corp.google.com/ci/kokoro/prod:cloud-devrel%2Fdotnet-docs-samples%2Flinux%2Fsystem_tests2/activity/440cfc15-74b4-4de2-be06-5a4cd43dd78d/log).

It seems like resources take longer to be available now?

**Comment by meredithslota** [comment]
There's an email from Karl on this, I'll loop you in.
