### ISSUE TITLE
Cloud Machine Learning Example

### ISSUE THREAD

**Issue by sguergachi** [GoogleCloudPlatform/dotnet-docs-samples#214]
Would really appreciate an example of how to make API calls to the Cloud ML platform using Google.Apis.CloudMachineLearningEngine.v1

Ideally the example would show how make a predict call (https://cloud.google.com/ml-engine/reference/rest/v1/projects/predict), which is something I think you would do frequently.

**Comment by SurferJeffAtGoogle** [comment]
https://cloud.google.com/prediction/docs/ says:
The Google Cloud Prediction API has been deprecated and will be shut down on April 30, 2018.
So we won't write such a sample.  :-(
