### ISSUE TITLE
All BigQuery samples should poll to wait for completion

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/dotnet-docs-samples#232]
There isn't really a difference between "sync/asynch" queries. I'm working to remove this distinction from the docs.

Please update all query samples to look more like this one, where they poll for results:

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/06d9eb392e600051145285aa73bb48a785e20666/bigquery/api/GettingStarted/BigqueryTest/BigqueryTest.cs#L164

Even if the "synchronous" request times out, the job is still running. Most people will want to wait for the results.

**Comment by tswast** [comment]
When creating a job, it's best to set an explicit Job ID, as well. (It should be unique, such as a UUID)

**Comment by jskeet** [comment]
The job ID is now always created automatically, and `GetQueryResults` waits for the job to complete before returning the `BigQueryResults` anyway now.
Closing as obsolete.
