### ISSUE TITLE
Return status of LongOperation

### ISSUE THREAD

**Issue by maciz84** [GoogleCloudPlatform/dotnet-docs-samples#238]
Hi Guys,

This is not an issue but more of a request for help. Does anyone know how I can return the progress or status of the long running  operation. Below is my current code but have no clue how to return the progress as I couldn't find it in the documentation. I am using Google.Cloud.Speech.V1.
`dynamic audiofile = "gs://mybucket/test2.wav";

dynamic speech = SpeechClient.Create();
dynamic longOperation = await speech.LongRunningRecognizeAsync(new RecognitionConfig {
	Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
	SampleRateHertz = 8000,
	LanguageCode = LanguageCodes.English.UnitedKingdom
}, RecognitionAudio.FromStorageUri(audiofile));
longOperation = await longOperation.PollUntilCompletedAsync();

dynamic response = longOperation.Result;

foreach (object result in response.Results) {

	foreach (object alternative in result.Alternatives) {
		txtReturn.Text = txtReturn.Text + alternative.Transcript;
		MyObservable.Add(new TranscriptionResult {
			Transcript = alternative.Transcript,
			Confidence = alternative.Confidence
		});

	}
}`

I appreciate your assistance with this.

**Comment by SurferJeffAtGoogle** [comment]
The current API does not provide any details about the partial progress of the operation.  The only thing you can observer is complete or incomplete.
