### ISSUE TITLE
Fix code style in all AIPlatform.Samples

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/dotnet-docs-samples#2622]
But I noticed that for the anonymous types initialization you are using something like JSON syntax by keeping the openening bracket on the same line as new? Also using parentheses on all the news.

In a separate PR, can you change that? So when you have things like:

Field = new() {
    Innerfield = value
}
do this instead?

Field = new
{
    Innerfield = value
}
On these samples and all the others. Thanks!

**Comment by jskeet** [comment]
There's a *huge* difference between `new() { ... }` and `new { ... }`. The former is a target-typed `new` expression, using an existing known type. The latter is an anonymous type initialization expression.

I agree with putting `{` on a new line... but please don't remove `()` thinking it's only about formatting.

**Comment by meteatamel** [comment]
@jskeet Thanks for the comment. I'm indeed just moving `{` to the next line and not changing `new()` to `new`.
