### ISSUE TITLE
SpeechContext appears to be read-only

### ISSUE THREAD

**Issue by keithpohl** [GoogleCloudPlatform/dotnet-docs-samples#263]
Using the RecognitionConfig object for speech recognition, we have not found a way to set the properties in a SpeechContext object in C#.  The Intellisense blocks us from setting any Phrases (or any other object) by only offering Read-Only properties (GETs).  We have seen no way to write to these properties (SETs).

Here is the example from one of our attempts:
![1](https://cloud.githubusercontent.com/assets/28535643/25817514/959370d6-33f5-11e7-998d-690d192452ce.jpg)

In this attempt, we were going to assign test to the SpeechContext as shown below:
![2](https://cloud.githubusercontent.com/assets/28535643/25817539/ad09eab0-33f5-11e7-8bd0-9d80eecf8e0b.jpg)

Thank you!

**Comment by SurferJeffAtGoogle** [comment]
See `RecognizeWithContext` in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/speech/api/Recognize/Recognize.cs for an example.  It looks like this:
```cs
            var config = new RecognitionConfig()
            {
                SpeechContexts = { new SpeechContext() { Phrases = { phrases } } },
                Encoding = RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = "en"
            };
```
