### ISSUE TITLE
Lag time in response

### ISSUE THREAD

**Issue by hikmatyar** [GoogleCloudPlatform/dotnet-docs-samples#275]
I'm using Node implementation of Google Speech to Text API, but the lag time is too much --- 3-4 seconds in response time. Is this normal? Is there a way to get it to less than 2 seconds?

**Comment by harshit7922** [comment]
hi hikmatyar,

please give me the code for 3-4 second. I am also trying to get in less than 2 second.

**Comment by SurferJeffAtGoogle** [comment]
Since you are you using the Node library, please report this issue here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/
