### ISSUE TITLE
proxy configuration 

### ISSUE THREAD

**Issue by rrc2k4** [GoogleCloudPlatform/dotnet-docs-samples#276]
How can we set proxy in speech sdk.we need to use proxy while consuming speech to text services and I have noticed that even setting proxy in web.config, sdk ignores it and hits google API directly ignoring proxy configuration.can u pls guide us on proxy configuration

**Comment by SurferJeffAtGoogle** [comment]
You can specify the http_proxy (yes, all lowercase) environment variable and gRPC will use HTTP's CONNECT to tunnel through the proxy.

**Comment by rrc2k4** [comment]
Thanks a lot.it worked.really appreciate your help on this.
