### ISSUE TITLE
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

### ISSUE THREAD

**Issue by Fevian48** [GoogleCloudPlatform/dotnet-docs-samples#2768]
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

View this [failed invocation](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/2767/checks?check_run_id=29127535115) of the CLA check for more information.

For the most up to date status, view the checks section at the bottom of the pull request.

_Originally posted by @google-cla[bot] in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/2767#issuecomment-2305305882_

**Comment by jskeet** [comment]
Spam...
