### ISSUE TITLE
Is there a way to see current rate-limit / usage on each VertexAI Gemini 1.5 Flash / Pro request?

### ISSUE THREAD

**Issue by fatihyildizhan** [GoogleCloudPlatform/dotnet-docs-samples#2841]
Hello,

Is there a way to see current rate-limit / usage on each VertexAI Gemini 1.5 Flash / Pro `predictionServiceClient.GenerateContentAsync()` request?

I am making requests for different content types like **string, pdf, audio, image** etc.

I try to monitor current usage from this dashboard: https://console.cloud.google.com/apis/api/aiplatform.googleapis.com/quotas

Am I using the dashboard incorrectly? When I get **429 Resource Exhausted**, the dashboard shows that I still have enough quota. In fact, most of the time it shows that I've only used a small portion of my quota.

There are different quotas for requests here, but they seem to be available most of the time.

Which services should I request more quota to solve the ResourceExhausted problem?
Thank you very much for your time.

![image](https://github.com/user-attachments/assets/3a01e190-dd42-4a4b-b39e-269006f048c7)

![image](https://github.com/user-attachments/assets/8752f06b-c0cc-451a-b1dd-3298caa7da6f)

![image](https://github.com/user-attachments/assets/89b9a25c-9667-4be1-904b-09af8d5a615d)

![image](https://github.com/user-attachments/assets/261c8c3f-057d-42ad-95df-551826bf2a8f)

**Comment by meteatamel** [comment]
I'm not sure of the answer. If you have a sample that consistently gives you `429 Resource Exhausted` at a certain rate, let me know here and I can see if it happens in my project

**Comment by fatihyildizhan** [comment]
I am sending a structured output request.

No consistency. Sometimes it gives an error but the quota shown on the dashboard is not full.

I assume the `429 Resource Exhausted` is related to **Seven-day peak usage > 90%**.

**Seven-day peak usage > 90%** is shown as 0. I think if I had exceeded the quota, this should not have been 0.

![image](https://github.com/user-attachments/assets/c5c1dbc7-f7aa-4170-99dc-27d12f045534)
--
`predictionServiceClient.GenerateContentAsync()`
Is there a field in the response of this request where we can see the current usage? For example, in the header etc.

**Comment by fatihyildizhan** [comment]
Maybe it is related to this https://github.com/langchain-ai/langchain/issues/22241#issuecomment-2502671076

[Dynamic shared quota](https://cloud.google.com/vertex-ai/generative-ai/docs/dsq)

**Comment by meteatamel** [comment]
Possibly. I don't know enough about how quotas work and how to check which quota is being hit. I'll ask internally to see if I can more info.

**Comment by meteatamel** [comment]
Ok, here's a blog post someone pointed out that explains the problem in detail: https://cloud.google.com/blog/products/ai-machine-learning/learn-how-to-handle-429-resource-exhaustion-errors-in-your-llms/

Basically, without provisioned throughput, you might run into 429, due to simply capacity running out.

**Comment by meteatamel** [comment]
Hi @fatihyildizhan, I'm closing this issue, as there's nothing we can do here as C# SDK team. Feel free to open again if you disagree.
