### ISSUE TITLE
Improve code coverage of spanner tests.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/dotnet-docs-samples#317]
Current tests cover only 44% of code.

![image](https://user-images.githubusercontent.com/11778530/29432872-0433a17c-8352-11e7-8d3e-cf6caf910ee5.png)

**Comment by SurferJeffAtGoogle** [comment]
Fixed.

**Comment by jskeet** [comment]
(Closing given the comment.)
