### ISSUE TITLE
Samples for flexible app engine and IISIntegration

### ISSUE THREAD

**Issue by plaisted** [GoogleCloudPlatform/dotnet-docs-samples#321]
It appears all of the samples provided for the flexible App Engine environment were created using "dotnet new" and as a result include a `web.config` and `.UseIISIntegration()` for Kestrel in the `Program.cs`.

From what I can tell based on the docker images the App Engine sets the PORT environmental variable in the container which is then exposed via docker and then Kestrel is set to use this port using the ASPNETCORE_URLS environmental variable via `ASPNETCORE_URLS=http://*:${PORT}`.

If this is the case and the `web.config` and IIS integration are not needed, I suggest removing them as being in the samples may suggest some IIS dependency.

**Comment by SurferJeffAtGoogle** [comment]
Good idea.  Thank you for the suggestion.
