### ISSUE TITLE
AppEngine flex samples run locally on windows

### ISSUE THREAD

**Issue by plaisted** [GoogleCloudPlatform/dotnet-docs-samples#325]
The samples for netcore on app engine flex all show running the apps in visual studio on a local windows machine. When the apps are deployed they are run on a debian8 linux container.

Although it is improving, the current state of cross platform support in netcore is not 100%. I've run into many issues moving code from windows to linux and had to implement workarounds. It would be helpful to show a sample of doing local development on a windows pc using the same linux containers that the app will be deployed under in the flex app engine.

This is relatively easy now with Docker for Windows and Docker tools for VS. If desired I can update a repo and submit a pull request.

**Comment by SurferJeffAtGoogle** [comment]
I've hit issues moving code from windows to linux too.  Such a demo would definitely be valuable to users.

A pull request would be awesome!

Please note, all contributors to this repo must accept the Google Contributer License Agreement here:
https://cla.developers.google.com/clas
It's only one page and not too intimidating.  So please have a look at it before beginning a pull request.

**Comment by asofolahan** [comment]
Hi @SurferJeffAtGoogle 
Thanks for sharing this .NET Vision API samples. I have issues setting up when I got to the ADC. Kindly help because I couldn't run my code.

Thanks
