### ISSUE TITLE
Endpoints Example Project fails to load in Visual Studio

### ISSUE THREAD

**Issue by StephenHodgson** [GoogleCloudPlatform/dotnet-docs-samples#401]
The [Endpoints example project](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/endpoints/getting-started) fails to load in Visual Studio Community 2017.

The issue was that the [global.json](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/endpoints/getting-started/global.json) file is using an incompatible version of the ASP.NET Core SDK.

The Fix:
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "2.0.0",
    "runtime": "coreclr"
  }
}
```

[Here's a blog post describing the issue in detail](https://andrewlock.net/the-sdk-microsoft-net-sdk-web-specified-could-not-be-found/).

**Comment by simonz130** [comment]
Thanks Stephen. 

I'm fixing the Endpoints sample now => porting it to .net core 2.0. Will update here once it's submitted.
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/441

**Comment by simonz130** [comment]
Hey Stephen,

I just merged the fix to this. Please, sync.
