### ISSUE TITLE
NAudio has conflict with speech api samples 

### ISSUE THREAD

**Issue by heathyates** [GoogleCloudPlatform/dotnet-docs-samples#425]
# Steps to Reproduce 

1.  Clone the repo and download 
2. Find the speech `sln` and load it 
3. When VS rebuilds the solution, you should the following error: 

`Package 'NAudio 1.8.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.`

# NAudio and .NET 2.0 seems to be the issue 

Please see this issue on NAudio as follows. Please see [here](https://github.com/naudio/NAudio/issues/285).

**Comment by SurferJeffAtGoogle** [comment]
Thank you for reporting this issue.

Were you able to successfully run the sample?  On Windows, Mac, or Linux?

**Comment by mofolom** [comment]
Bump.

Did the same. Cloned the repo and tried to rebuild the solution.

**Comment by SurferJeffAtGoogle** [comment]
mofolom, could you reply with your build output?

**Comment by shaikhnizam** [comment]
I'm also facing same error while trying to resolve Nuget issue. Any solutions??

warning NU1701: Package 'NAudio 1.8.4' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by dfdumaresq** [comment]
I'm having the same issue.

**Comment by helloneoberg** [comment]
You may wish to refer to this link: https://markheath.net/post/naudio-netstandard
Look under "Try it out!" section as it guide you to use the preview package.
The sample i downloaded is working now with the preview package from NuGet.
Hope it help..

**Comment by SurferJeffAtGoogle** [comment]
I see the same warning:

```
$ dotnet test
/usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/Recognize/Recognize.csproj : warning NU1701: Package 'NAudio 1.8.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [/usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/SpeechTest/SpeechTest.csproj]
/usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/SpeechTest/SpeechTest.csproj : warning NU1701: Package 'NAudio 1.8.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Build started, please wait...
/usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/SpeechTest/SpeechTest.csproj : warning NU1701: Package 'NAudio 1.8.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/Recognize/Recognize.csproj : warning NU1701: Package 'NAudio 1.8.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Build completed.
```

But the code still runs and succeeds:
```
est run for /usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/SpeechTest/bin/Debug/netcoreapp2.0/SpeechTest.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.7.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
QuickStart 
Recognize sync resources/audio.raw
Recognize sync resources/audio.raw
Recognize rec -e Flac resources/audio.flac
Recognize sync-creds resources/audio.raw <redacted>
Recognize async -w gs://vqjemsdhjjalaypdrhif/audio.raw
Recognize with-context resources/audio.raw
Recognize sync -p resources/commercial_mono.wav
Recognize async gs://vqjemsdhjjalaypdrhif/audio.raw
[xUnit.net 00:00:36.82]     GoogleCloudSamples.LocalRecognizeTests.TestStreaming [SKIP]
Skipped  GoogleCloudSamples.LocalRecognizeTests.TestStreaming
Recognize sync -m command_and_search resources/audio.raw
Recognize sync -w resources/audio.raw
Recognize sync -c 2 resources/commercial_stereo.wav
[xUnit.net 00:00:58.77]     GoogleCloudSamples.LocalRecognizeTests.TestListen [SKIP]
Skipped  GoogleCloudSamples.LocalRecognizeTests.TestListen

Total tests: 14. Passed: 12. Failed: 0. Skipped: 2.
Test Run Successful.
Test execution time: 1.0937 Minutes
```

If I try upgrading to version `1.9.0-preview1`, then I see a compile error:
```
$ dotnet test
Build started, please wait...
Recognize.cs(487,17): error CS0234: The type or namespace name 'WaveIn' does not exist in the namespace 'NAudio.Wave' (are you missing an assembly reference?) [/usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/speech/api/Recognize/Recognize.csproj]
```

So, yes, I see the warning, but I'm not sure what to do about it.  The code works on Windows, and is skipped on Linux, and I see no better possible behavior.  Is there a better solution?

**Comment by jskeet** [comment]
Note: NAudio 1.9.0 will target netstandard2.0 directly, but it's not out yet.

I suggest we leave this issue open until 1.9.0 is out, then update the sample to depend on that, at which point the warning should go away. (I note that Jeffrey tried with 1.9.0-preview1 before, but when 1.9.0 is actually out we can make any changes needed.)

**Comment by jskeet** [comment]
(Issue with Wave.WaveIn is still an issue with 1.9.0-preview2.)
