### ISSUE TITLE
warning NU1701: Package 'EnterpriseLibrary.TransientFaultHandling 6.0.1304' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. 

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/dotnet-docs-samples#434]
When building the Spanner project.  Far from fatal, but we should be using https://www.nuget.org/packages/TransientFaultHandling.Core/

**Comment by SurferJeffAtGoogle** [comment]
Hmm.  That library was last updated in 2012, so we may need to find another one.

**Comment by simonz130** [comment]
I've had the same error for BigQuery project. Fixed it there to use Retrier from TestUtils. I'll fix this too.

**Comment by simonz130** [comment]
Submitted PR: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/571

**Comment by mjr2001us** [comment]
Warning	NU1701	Package 'Antlr 3.4.1.9004' was restored using '.NETFramework,Version=v4.6.1 in MVC5 ,netcore
