### ISSUE TITLE
Speech client wrapper, missing method: ToChannelCredentials

### ISSUE THREAD

**Issue by mofolom** [GoogleCloudPlatform/dotnet-docs-samples#436]
![image](https://user-images.githubusercontent.com/4580013/35659946-cb6a0fb8-0711-11e8-8ab4-f711add14c88.png)

How do i resolve this?

**Comment by simonz130** [comment]
Have you tried to do "dotnet restore" and then recompile the entire sample? Typically issues like "method not found" mean that you try to use older assembly version than the one containing that method that is not found.

**Comment by mofolom** [comment]
late response but thanks i got it working. "dotnet restore" worked.

**Comment by simonz130** [comment]
Great!
