### ISSUE TITLE
Credential Error: Error deserializing JSON credential data

### ISSUE THREAD

**Issue by RickCooke** [GoogleCloudPlatform/dotnet-docs-samples#444]
Hi,
I'm using the vision api (via ImageAnnotatorClient) and upon instantiating I get the following error: 
"Error reading credential file from location [PATH]: Error deserializing JSON credential data.\nPlease check the value of the Environment Variable GOOGLE_APPLICATION_CREDENTIALS"
Problem is, I cloned the vision api sample in this repo and that runs just fine so I know that the environment variable is set correctly and that the info inside my credential file is in the right format. Both where I want to use this in my own code (not working) and in the test code (working) have the same code:
```
// Instantiates a client
var client = ImageAnnotatorClient.Create();
// Load the image file into memory
Image image = Image.FetchFromUri(url);
//Performs label detection on the image file
var response = client.DetectLabels(image);
```
and have the same version of Newtonsoft.Json (10.0.2) and target the same framework (.net 4.5). My failure is coming from the first line.

Note: Maybe its worth mentioning that the error producing code is contained within a Class Library project that is used by a Console Application project and the working code is directly in the Console Application.

**Comment by simonz130** [comment]
Hey Rick,

Can you please open CMD and run SET command? Is the output of SET including GOOGLE_APPLICATION_CREDENTIALS variable? If yes, is the value of the variable a valid full file path? (Not relative path)

**Comment by RickCooke** [comment]
Yep. The variable is set to a full and correct path. In fact: as a sanity check I've introduced the following like of code before the client instantiation in both projects with the same result
`            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", @"[PATH]");
`

**Comment by simonz130** [comment]
Alright, thanks for confirmation. I'll take a look and report back here.

**Comment by jskeet** [comment]
@RickCooke: Can I check whether you're still running into this problem? My guess is that it was a problem with assembly binding redirects, but I'm happy to help with the diagnosis if it's still an issue. (Otherwise, we can close the issue.)

**Comment by jskeet** [comment]
Closing as stale. Please add a comment with more information if you still need assistance, and I'll reopen the issue.
