### ISSUE TITLE
Sample for DataStore - Parents

### ISSUE THREAD

**Issue by BoasE** [GoogleCloudPlatform/dotnet-docs-samples#468]
Hi

is there an example for how to use entitygroups / parents with datastore ?
currently just can't find one. Am I overseeing something?

**Comment by jskeet** [comment]
@BoasE: There's an example of an ancestor query at https://cloud.google.com/datastore/docs/concepts/queries#ancestor_queries if that's what you were looking for.
If not, and if this is still relevant to you, please could you give more details of what you're trying to achieve? I'll either try to find an existing sample for you, or let you know the code I'd expect to work and we can build a sample later.

**Comment by jskeet** [comment]
Closing as stale. Please add a comment with more information if you still need assistance, and I'll reopen the issue.
