### ISSUE TITLE
On textDetection sample don't work on Thai Language

### ISSUE THREAD

**Issue by xamaringeek** [GoogleCloudPlatform/dotnet-docs-samples#50]
Hi Google cloud team,

On textDetection sample don't work on Thai Language.
Can't translate on the message.

**Question:** 
1) It's support only english language ? 
2) How we can modify the source code for support other language ? 

Thanks you

**Comment by SurferJeffAtGoogle** [comment]
It supports 80 languages.  I'm in the process of confirming that Thai is one of them.

In this code:
```
                Config = new Google.Apis.CloudSpeechAPI.v1beta1.Data.RecognitionConfig()
                {
                    Encoding = "LINEAR16",
                    SampleRate = 16000,
                    LanguageCode = "en-US"
                },
```

Have you tried setting the `LanguageCode` to `th` instead of `en-US`?

**Comment by xamaringeek** [comment]
Thanks you, but i used on Google vision, don't have .**ReconginitionConfig**() method ?

_using Google.Apis.Auth.OAuth2;
using Google.Apis.Services;
using Google.Apis.Vision.v1;
using Google.Apis.Vision.v1.Data;_

Please suggestions

**Comment by xamaringeek** [comment]
https://cloud.google.com/vision/docs/quickstart 
try this it's worked.
