### ISSUE TITLE
Running against the google cloud datastore emulator

### ISSUE THREAD

**Issue by naasking** [GoogleCloudPlatform/dotnet-docs-samples#522]
There don't appear to be any samples that run against the [datastore emulator](https://cloud.google.com/datastore/docs/tools/datastore-emulator). I've tried connecting manually to the local IP and port, but it doesn't seem to work.

**Comment by jskeet** [comment]
It *should* work fine - and as of `Google.Cloud.Datastore.V1` version 2.2.0-beta02 you should be able to connect to the emulator much more easily - see http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Datastore.V1/#beta-support-for-emulator-detection

I'm going to close this issue now as a) you may well no longer even be using Datastore or the emulator; b) it should be solved by the above. If you run into any problems, do please add a comment with more details and I can reopen the issue (or file another one at https://github.com/googleapis/google-cloud-dotnet)
