### ISSUE TITLE
Memory leak issue while publishing message

### ISSUE THREAD

**Issue by muralirly** [GoogleCloudPlatform/dotnet-docs-samples#547]
Hi,
The memory size is increasing and crashing the application at the below line.

 publishTasks.Add(publisher.PublishAsync(text));

Any idea how to clear the memory after a message? We have to send 1000's of records in a minute and the memory is keep on increasing.

**Comment by SurferJeffAtGoogle** [comment]
Move issue to library repo: https://github.com/googleapis/google-cloud-dotnet/issues/2532
