### ISSUE TITLE
current version of library supported

### ISSUE THREAD

**Issue by CJMedina** [GoogleCloudPlatform/dotnet-docs-samples#548]
Issue:
 Customer is retrieving data from his Datastore using C# and with sorting order but encountering:

-----
“Google.Cloud.Datastore.V1.Filter.And(Google.Cloud.Datastore.V1.Filter.Equal("done", false), Google.Cloud.Datastore.V1.Filter.GreaterThanOrEqual("priority", 4)),”

According to the [1] documentation, Google.Cloud.Datastore.V1.Filter.And() takes an array of Filter objects.

```text
And(Filter[])
Creates a composite filter which is the logical "AND" of all the specified filters.

Declaration
public static Filter And(params Filter[] filters)
Parameters
Type	Name	Description
Filter[]	filters	
Set of filters to combine. Must not be null or empty, or contain null references.

Returns
Type	Description
Filter	
A filter representing the logical "AND" of all the elements in filters.
```
-----

Source code:
running in C# under .net core

```csharp
Google.Cloud.Datastore.V1.Query myQuery = new Google.Cloud.Datastore.V1.Query(Kind)
{
    Filter = Google.Cloud.Datastore.V1.Filter.And(Google.Cloud.Datastore.V1.Filter.GreaterThan("Modified", new DateTime(2018, 5, 9, 0, 0, 0, DateTimeKind.Utc)), Google.Cloud.Datastore.V1.Filter.LessThan("Modified", new DateTime(2018, 5, 10, 0, 0, 0, DateTimeKind.Utc))),
    //Order = { {"Modified", Google.Cloud.Datastore.V1.PropertyOrder.Types.Direction.Descending } } 
};
```

-----
Just to reiterate the problem is that the The following declartion fails

```csharp
Google.Cloud.Datastore.V1.Query query = new Google.Cloud.Datastore.V1.Query("Task")
{
    Filter = Google.Cloud.Datastore.V1.Filter.And(Google.Cloud.Datastore.V1.Filter.Equal("done", false), Google.Cloud.Datastore.V1.Filter.GreaterThanOrEqual("priority", 4)),
    Order = { { "priority", Google.Cloud.Datastore.V1.PropertyOrder.Types.Direction.Descending } }
};
```
           
The reason it fails is because the ORDER property of the QUERY class is get; only NOT get; set;  (ie read only)

So in the Query class there appears to be NO WAY to set an Order in the query. UNLESS this is an issue with current version of library support. Client has copied and followed the docs - [2]

-----

[1] https://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Datastore.V1/api/Google.Cloud.Datastore.V1.Filter.html#methods
[2] https://cloud.google.com/datastore/docs/concepts/queries#query_structure

**Comment by jskeet** [comment]
(I realize this is an old issue and may be obsolete, but the information below could be useful anyway.)

That code should compile fine normally - even though `Order` is read-only, the collection initializer is *adding* to it, in this case via an extension method. You haven't specified the error message, but given that you're fully-qualifying all the rest of the names, I wonder whether you don't have a `using` directive for `Google.Cloud.Datastore.V1`, which means you're not picking up the `Add` method in `QueryExtensions`.

Simply add

```csharp
using Google.Cloud.Datastore.V1;`
```

at the top of the file and it should be fine. You can then simplify the code to:

```csharp
Query query = new Query("Task")
{
    Filter = Filter.And(Filter.Equal("done", false), Filter.GreaterThanOrEqual("priority", 4)),
    Order = { { "priority", PropertyOrder.Types.Direction.Descending } }
};
```

Closing as the library is working as intended.
