### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail=\"Connect Failed\")

### ISSUE THREAD

**Issue by bvijaybhargav** [GoogleCloudPlatform/dotnet-docs-samples#549]
I am getting the following error in "await streamingCall.WriteAsync" Call. I am beginner so please bare with me. 
"Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail=\"Connect Failed\")\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()"

I am not able to proceed further. pls help.

I have created and downloaded Json key file.

**Comment by lorienpatt** [comment]
I am also having this issue.  Following

**Comment by jskeet** [comment]
Hi folks, I've only just become aware of this issue. If this is a problem you're having with the client libraries, could you file an issue at https://github.com/googleapis/google-cloud-dotnet and give more context about what you're trying to do, including which API you're using? A complete example would be particularly helpful, along with context about where your code is running (locally, on GCP, elsewhere etc).

**Comment by jskeet** [comment]
Closing as stale. Please add a comment with more information if you still need assistance, and I'll reopen the issue.
