### ISSUE TITLE
Multiple StreamingRecognizeRequest

### ISSUE THREAD

**Issue by pogs17** [GoogleCloudPlatform/dotnet-docs-samples#561]
I'm trying to setup a StreamingRecognize, with multiple request's. Is it possible ?

The point is that i want to send audio stream from the mic with a unknown time, so i think that i must implement multiple requests. (Considering that a request session has a max_time = 65 seconds).

Anyone can help me with this ?

Thank's alot ;)

Google sample code:
```cs
static async Task<object> StreamingMicRecognizeAsync(int seconds)
{
if (NAudio.Wave.WaveIn.DeviceCount < 1)
{
    Console.WriteLine("No microphone!");
    return -1;
}
var speech = SpeechClient.Create();
var streamingCall = speech.StreamingRecognize();
// Write the initial request with the config.
await streamingCall.WriteAsync(
    new StreamingRecognizeRequest()
    {
        StreamingConfig = new StreamingRecognitionConfig()
        {
            Config = new RecognitionConfig()
            {
                Encoding =
                RecognitionConfig.Types.AudioEncoding.Linear16,
                SampleRateHertz = 16000,
                LanguageCode = "en",
            },
            InterimResults = true,
        }
    });
// Print responses as they arrive.
Task printResponses = Task.Run(async () =>
{
    while (await streamingCall.ResponseStream.MoveNext(
        default(CancellationToken)))
    {
        foreach (var result in streamingCall.ResponseStream
            .Current.Results)
        {
            foreach (var alternative in result.Alternatives)
            {
                Console.WriteLine(alternative.Transcript);
            }
        }
    }
});
// Read from the microphone and stream to API.
object writeLock = new object();
bool writeMore = true;
var waveIn = new NAudio.Wave.WaveInEvent();
waveIn.DeviceNumber = 0;
waveIn.WaveFormat = new NAudio.Wave.WaveFormat(16000, 1);
waveIn.DataAvailable +=
    (object sender, NAudio.Wave.WaveInEventArgs args) =>
    {
        **I WANT TO PERFORM A NEW REQUEST HERE**
        lock (writeLock)
        {
            if (!writeMore) return;
            streamingCall.WriteAsync(
                new StreamingRecognizeRequest()
                {
                    AudioContent = Google.Protobuf.ByteString
                        .CopyFrom(args.Buffer, 0, args.BytesRecorded)
                }).Wait();
        }
    };
waveIn.StartRecording();
Console.WriteLine("Speak now.");
await Task.Delay(TimeSpan.FromSeconds(seconds));
// Stop recording and shut down.
waveIn.StopRecording();
lock (writeLock) writeMore = false;
await streamingCall.WriteCompleteAsync();
await printResponses;
return 0;
}
```

**Comment by SurferJeffAtGoogle** [comment]
So, you want to send a continuous stream, that may be longer than 65 seconds?

**Comment by pogs17** [comment]
@SurferJeffAtGoogle Yes! I want to speech a report using stream from microphone. I was searching about this a couple of weeks, and the only tip that i saw is that i can do multiple requests .. I found a web example doing exactly what i want, but i need do this using c#.

Web sample: [https://www.google.com/intl/pt/chrome/demos/speech.html](url)

Thanks in advance for trying to help me Jeff! (:

**Comment by mahi7891122330** [comment]
If you are doing this in winform
You can do it in a while loop until the user press the stop button.

//declare public variable to exit the loop
 public bool Iscancelled  = false;
 private async void btnStart_Click(object sender, EventArgs e)
        {
                Iscancelled = false;
                btnStart.Enabled = false;
                btnStop.Enabled = true;
 while (!Iscancelled)
            {
              try
                {
                    x = new object();
                    x = await StreamingMicRecognizeAsync(seconds);
                  try
                    {
                        if ((int)x == -1)//No Microphone
                        {
                            Iscancelled = true;
                        }
                    }
                    catch
                    { }
                }
                catch (Exception ex)
                {
 }
}
}

  private void btnStop_Click(object sender, EventArgs e)
        {
            Iscancelled = true;
            btnStop.Enabled = false;
         }
