### ISSUE TITLE
Improve .NET Cloud Vision Samples README

### ISSUE THREAD

**Issue by meteatamel** [GoogleCloudPlatform/dotnet-docs-samples#576]
.NET Cloud Vision Samples (https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/vision/api) require that you have default application credentials enabled and an environment variable is set to point to it for samples to work. 

It's not that clear in its README that this is a requirement. The README says "Follow the instructions in the root README" and the root README talks about application credentials. However, this is very easy to miss. I suggest that we have a third step in README like this:

1. Follow the instructions in the root README.
2. Enable APIs for your project. Click here to visit Cloud Platform Console and enable the Google Cloud Vision API.
3. Make sure you have application default credentials setup, as explained in the root README.

**Comment by SurferJeffAtGoogle** [comment]
We're no longer expecting users to run samples.  The instructions aren't perfect.  But we have more important to bugs to fixed.

**Comment by meteatamel** [comment]
Users not expected to run samples?
