### ISSUE TITLE
Code snippets for IAM

### ISSUE THREAD

**Issue by awkoren** [GoogleCloudPlatform/dotnet-docs-samples#578]
There are currently no samples available for IAM. This is needed for the documentation: https://cloud.google.com/iam/docs/.
I work on the docs in question and can write the snippets as needed.

**Comment by SurferJeffAtGoogle** [comment]
Alexander, are the snippets complete?  Can we close this bug?

**Comment by awkoren** [comment]
Yup all set, thanks.
