### ISSUE TITLE
Add README and tests to pet shop application.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/dotnet-docs-samples#604]
Tests need only confirm the code compiles without error.

**Comment by simonz130** [comment]
This is in progress but currently the test on Windows fails due to .NET Framework 2.0 issue with permissions https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/833

**Comment by simonz130** [comment]
Closing this as it's not feasible. The code compiles but it's so old (that's the point of the demo) so that we can't easily test it.
