### ISSUE TITLE
Datastore TaskList sample checks for 2 command line args, should check for 1

### ISSUE THREAD

**Issue by WalterHub** [GoogleCloudPlatform/dotnet-docs-samples#61]
The check for a command line argument looks for 2 args, so it exits if a single arg (for the project id) is supplied.

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/datastore/api/TaskList/Program.cs#L171

**Comment by SurferJeffAtGoogle** [comment]
Fixed in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/59
