### ISSUE TITLE
Cloud Firestore samples use older library version; SnapshotAsync is now GetSnapshoAsync

### ISSUE THREAD

**Issue by jlara310** [GoogleCloudPlatform/dotnet-docs-samples#651]
Include="Google.Cloud.Firestore" Version="1.0.0-beta02"

Latest version is:
Include="Google.Cloud.Firestore" Version="1.0.0-beta11"

However, updating to the newer version causes samples to fail.

For example, in firestore/api/Quickstart:
dotnet run retrieve-all-documents <my-project>

Program.cs(82,53): error CS1061: 'CollectionReference' does not contain a definition for 'SnapshotAsync' and no accessible extension method 'SnapshotAsync' accepting a first argument of type 'CollectionReference' could be found 

This error is fixed by changing SnapshotAsync to GetSnapshotAsync.

**Comment by jskeet** [comment]
Looks like this has already been fixed.
