### ISSUE TITLE
README.md Build and Run with Google Cloud Shell

### ISSUE THREAD

**Issue by gianghnd** [GoogleCloudPlatform/dotnet-docs-samples#653]
The instruction said that:
"Upload your JSON key file to Cloud Shell:

Use the Cloud Shell file browser to select the dotnet-doc-samples folder.
Use the File menu to select Import > File or Zip Archive"

However, I can't select File menu to select Import. It displays Export.

Please help to update README.md

Thanks,
Giang Hoa
![speechapi_01](https://user-images.githubusercontent.com/10970434/46572675-34af4c80-c9b4-11e8-8a74-c646516bcc09.png)
![speechapi_02](https://user-images.githubusercontent.com/10970434/46572676-34af4c80-c9b4-11e8-8fd7-21e4277e6ccb.png)

**Comment by amanda-tarafa** [comment]
@gianghnd Sorry for the delay on this.
Are you still experiencing this issue?

**Comment by amanda-tarafa** [comment]
@gianghnd I will be closing since we haven't heard anything. Please leave a comment if you are still having trouble so we can reopen.
