### ISSUE TITLE
TestBatchGetAssetsHistory() is broken.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/dotnet-docs-samples#692]
I'll change the code to skip the test, but we should get to the bottom of the test failure.

**Comment by SurferJeffAtGoogle** [comment]
Peter.  Could you please fix?

**Comment by peter-zheng-g** [comment]
Is there anyway I can trigger the test to verify any possible fix I would possibly have? As communicated it always passes on my local machine.

**Comment by SurferJeffAtGoogle** [comment]
Yes.  Create a pull request that stops skipping the test.  Label it with `DO NOT MERGE`.  A pre-submit test will automatically run.

**Comment by amanda-tarafa** [comment]
@peter-zheng-g ping on this. Can you please try and fix the broken test.

**Comment by amanda-tarafa** [comment]
Closing in favour of #1141 now that tests have been migrated to the new canonical.
