### ISSUE TITLE
Sample app not working with latest version of google.cloud.logging.log4net

### ISSUE THREAD

**Issue by jatin1080** [GoogleCloudPlatform/dotnet-docs-samples#697]
I've tried running the sample app (https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/logging/api/Log4Net) for logging through log4net to send logs from GCE instance to Stackdriver. The app works fine but I noticed that the version of library google.cloud.logging.log4net used is 1.0.0-beta05. I tried updating the library version to the latest stable 2.2.1 version(by updating the corresponding NuGet package). The application is not able to send logs when running through a GCE instance. Are there any changes that need to done in the code after updating the library version?

**Comment by SurferJeffAtGoogle** [comment]
I [upgraded all the nuget dependencies](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/712), and [deployed to Compute Engine](http://104.197.30.64/).

Log entries appear:
![image](https://user-images.githubusercontent.com/11778530/49617940-7c7a3200-f96b-11e8-8777-21b603c089d7.png)

Note that **GCE VM Instance** must be selected to see the log statement.

Also, double check that your VM has a service account.  In Google Cloud Console's VM Instance details page, near the bottom, it should list a service account.

Also, did you create your IIS server with this launcher?
https://pantheon.corp.google.com/marketplace/details/click-to-deploy-images/aspnet
That will set it up with a service account and all the right permissions.

**Comment by jskeet** [comment]
@jatin1080: Are you still facing this problem? I'd be happy to look into it if so; otherwise, I'll close the issue.

**Comment by jskeet** [comment]
Closing as stale. Please add a comment with more information if you still need assistance, and I'll reopen the issue.
