### ISSUE TITLE
Spanner.sln is missing two projects

### ISSUE THREAD

**Issue by jpharaoh-google** [GoogleCloudPlatform/dotnet-docs-samples#723]
I get an error when I try to follow these instructions, specifically when building Spanner.sln:

https://cloud.google.com/spanner/docs/getting-started/csharp/

The error goes away if I add the following two projects to the solution, both present in this repository:

- commandlineutil\Lib\CommandLineUtil.csproj
- testutil\testutil.csproj.

It seems that the solution file should include these projects.

**Comment by SurferJeffAtGoogle** [comment]
Thank you for reporting this issue.  A fix is on the way...
