### ISSUE TITLE
Integrating Google Speech to text in googlehome interaction

### ISSUE THREAD

**Issue by SanaWaseem** [GoogleCloudPlatform/dotnet-docs-samples#738]
Can you please guide how to integrate google speech to text in the way you have integrated other google apis with .net containers?

**Comment by teepong** [comment]
บ้าน

**Comment by SurferJeffAtGoogle** [comment]
SanaWaseem, 

Thank you for the request.

To help clarify, could you point me to another integration that we can use as a model of what you seek?

**Comment by jskeet** [comment]
Closing as stale. Please add a comment with more information if you still need assistance, and I'll reopen the issue.
