### ISSUE TITLE
Is it possible to debug it locally?

### ISSUE THREAD

**Issue by SanaWaseem** [GoogleCloudPlatform/dotnet-docs-samples#742]
Okay, so I created an ngrok URL and set it in the dialogFlow fulfillment webhook but i want to debug the application but the break point never hits the conversation controller. Can you please guide how to do that,

**Comment by jskeet** [comment]
Can I ask if you're still facing this problem? If so, could you please provide more context in terms of the steps you've gone through? Does your web hook work when running elsewhere? Are you able to *run* with ngrok but not debug?
(As a general note, for further questions that aren't specific to the samples, please add the issue to https://github.com/googleapis/google-cloud-dotnet which is the repository for the client libraries themselves.)

**Comment by jskeet** [comment]
Closing as stale. Please add a comment with more information if you still need assistance, and I'll reopen the issue.
