### ISSUE TITLE
Method is recursive on all execution paths

### ISSUE THREAD

**Issue by tstivers1990** [GoogleCloudPlatform/dotnet-docs-samples#753]
This can't be right...

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/d6177e7ccae7a582cf66b1e0740487ca93b63715/kms/api/CloudKmsAspNetSample/Services/EncryptedFileProvider.cs#L63-L71

**Comment by SurferJeffAtGoogle** [comment]
Thanks for catching this.  Working on a fix...

**Comment by tstivers1990** [comment]
@SurferJeffAtGoogle Thank ReSharper :P

**Comment by tstivers1990** [comment]
That said, I ended up just changing the code to `throw new NotImplementedException();` and it worked, at least for my use case. I'm not familiar enough with the code to know if that function was ever intended to be implemented or not.

**Comment by jskeet** [comment]
Closing as this was fixed by #796.
