### ISSUE TITLE
VB.net StreamingRecognize Mic

### ISSUE THREAD

**Issue by MartinHolmes82** [GoogleCloudPlatform/dotnet-docs-samples#800]
Is there any guides on a VB.net version of the streaming recognize? Struggling to convert the C#. Thanks

**Comment by jskeet** [comment]
No, I'm afraid we don't have any VB samples that I'm aware of. I'd expect online converters to work reasonably though. Is there any specific piece of code that's causing problems?

**Comment by MartinHolmes82** [comment]
I've tried the online converters but I get quite a few syntax errors. It's just around the logic of calling the different tasks to run asynchronous. I'll have another look. Thanks for responding so quickly.

**Comment by jskeet** [comment]
Hi Martin - any update on this? Do you still need assistance? If you could post the specific chunk of code that's causing problems, I can try to convert it myself.

**Comment by jskeet** [comment]
Closing for the moment due to lack of information. We can always open this up again when we have a more concrete piece of code to help with.
