### ISSUE TITLE
[Trace/Api] Outdated: port binding incorrect; deployment incorrect

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/dotnet-docs-samples#810]
Source:
https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/trace/api

I'm diverging from the documentation by using Microsoft's container image `microsoft/dotnet:2.2-sdk` but -- IIUC -- this should not affect the behavior I observe:

### Port bindings

The documentation references `dotnet run` will bind to `:5000`:
```
Now listening on: http://localhost:5000
```
In my experience, the default port binding is `:80`:
```
Hosting environment: Production
Content root path: /dotnet
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```
Curiously, neither of these would work for App Engine Flex which assumes `:8080`.

One solution is to revise `Program.cs` to be:
```csharp
public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseUrls("http://0.0.0.0:8080")
        .Build();
```

### App Engine

The deployment command is out-of-date and (for Linux) may be replaced with:
```bash
gcloud app deploy ./bin/Debug/netcoreapp2.0/publish/app.yaml \
--project=${PROJECT}
```

### Cloud Run

We may wish to consider documenting deploying the solution to [Cloud Run](https://cloud.google.com/run/). I took the container image generated by Flex and deployed this to Cloud Run and -- as expected -- it works there too.

**Comment by SurferJeffAtGoogle** [comment]
ASP.NET core has made answering the simple question, "Which port will it bind to?" quite difficult.  For example, see https://github.com/aspnet/AspNetCore/issues/4159 and https://josephwoodward.co.uk/2017/02/many-different-ways-specifying-host-port-asp-net-core.

For this particular code sample, when I run it locally, it runs on port 5000.

```sh
$ dotnet run
Hosting environment: Production
Content root path: /usr/local/google/home/rennie/gitrepos/dotnet-docs-samples/trace/api
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

I tried following the current instructions in this README, and the app successfully deployed to App Engine Flex.

To use a custom container image, like `microsoft/detnet:2.2-sdk`, you'll also have to set the environment variable ASPNETCORE_URLS, as described here:
https://cloud.google.com/appengine/docs/flexible/dotnet/runtime

I'm also working on Cloud Run samples.  For example, https://github.com/GoogleCloudPlatform/getting-started-dotnet/tree/master/Bookshelf.  Sadly, in that case, it requires custom code in `Program.cs`.

When Cloud Run graduates from Beta and is available in more locations, I plan to update lots of docs.
