### ISSUE TITLE
Sample dot-net code for Google AutoML Natural Language

### ISSUE THREAD

**Issue by devna13** [GoogleCloudPlatform/dotnet-docs-samples#819]
I'm trying to build a custom content classification using AutoML. Can AutoML API be accessed  with LanguageServiceClient similar to dotnet-docs-samples/language/api/Analyze/Program.cs  examples ?

**Comment by jskeet** [comment]
No, the AutoML API is separate to the Natural Language API. We don't currently have a .NET client library for AutoML; you could *try* generating one yourself based on the [proto definitions](https://github.com/googleapis/googleapis/tree/master/google/cloud/automl/v1beta1) and the [instructions for adding an API to the google-cloud-dotnet repository](https://github.com/googleapis/google-cloud-dotnet/blob/master/NEWAPI.md). I view it as likely that we'll generate a .NET client library for AutoML when it comes out of beta.
