### ISSUE TITLE
How do I run QuickStart.exe?

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [GoogleCloudPlatform/dotnet-docs-samples#840]
In the readme file here [Google Cloud Speech API Samples](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/vs2015/speech/api#google-cloud-speech-api-samples), it says under Build and Run:

5. From the command line, run QuickStart.exe:

>     PS C:\...\dotnet-docs-samples\speech\api> cd .\QuickStart\bin\Debug\
>     PS C:\...\dotnet-docs-samples\speech\api\QuickStart\bin\Debug> .\QuickStart.exe
>     how old is the Brooklyn Bridge

I get an error when I type in the command line on Windows 10:

> PS -help

that says

> 'PS' is not recognized as an internal or external command, operable program or batch file.

I did a search on the internet for PS. I didn't get anything.

Could someone explain?

**Comment by jskeet** [comment]
The "PS" is indicating running it in PowerShell. Many of scripts in this repo use PowerShell, but for the example you're using, you don't need to.
Just follow the [master branch documentation](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api) and you should be fine.
