### ISSUE TITLE
QuickStart.exe is not built and cannot be found.

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [GoogleCloudPlatform/dotnet-docs-samples#841]
At [Build and Run - Google Cloud Speech API Samples](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/vs2015/speech/api#build-and-run).

I was able to proceed up to step four, but there is no QuickStart.exe to find after that.

What am I doing wrong?

**Comment by jskeet** [comment]
You're looking in the vs2015 branch (last updated in 2017) - are you trying to use VS2015, or are you on a more modern version of Visual Studio? The [documentation in the master branch](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api) shows using `dotnet run` to run the sample.

**Comment by Shinehah-Gnolaum** [comment]
I'm using Visual Studio 2019 on my PC. I'm using Visual Studio for Mac on my Mac mini also. I'm trying whatever I can get to work.

**Comment by jskeet** [comment]
Right. In that case you definitely don't want to be using the old vs2015 branch. You will need the .NET Core SDK installed though.

If you just run `dotnet run` from the QuickStart directory, it should work fine. (Even the `dotnet restore` step is unnecessary with recent versions of the .NET Core SDK.)

**Comment by jskeet** [comment]
Closing as I believe just using the recent branch should be fine.
