### ISSUE TITLE
ERROR(S): No verb selected.

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [GoogleCloudPlatform/dotnet-docs-samples#843]
I get the following in the Command Line Console in Windows 10 when I run Recognize sample using Visual Studio 2019:

Recognize 1.0.0
Copyright (C) 2019 Recognize
ERROR(S):
No verb selected.

  sync            Detects speech in an audio file.

  async           Creates a job to detect speech in an audio file, and waits
                  for the job to complete.

  stream          Detects speech in an audio file by streaming it to the Speech
                  API.

  listen          Detects speech in a microphone input stream.

  rec             Detects speech in an audio file. Supports other file formats.

  sync-creds      Detects speech in an audio file.

  with-context    Detects speech in an audio file. Add additional context on
                  stdin.

  help            Display more information on a specific command.

  version         Display version information.

C:\Program Files\dotnet\dotnet.exe (process 19600) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .

The Output Window in Visual Studio gives this:

'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\dbrow_000\dotnet-docs-samples-master\speech\api\Recognize\bin\Debug\netcoreapp2.0\Recognize.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\dbrow_000\.nuget\packages\commandlineparser\2.3.0\lib\netstandard1.5\CommandLine.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\dbrow_000\.nuget\packages\google.cloud.speech.v1\1.1.0\lib\netstandard1.5\Google.Cloud.Speech.V1.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Globalization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Reflection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Reflection.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.11\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[19600] dotnet.exe' has exited with code 1 (0x1).

**Comment by jskeet** [comment]
I didn't write the sample, but I believe it's expecting you to provide one of those options on the command line. If you want to run the code within Visual Studio, go into the Properties window for the project, then under the "Debug" tab, in the "Application arguments" textbox, enter the command line arguments you want to use. Or run it from the command line instead, of course.

**Comment by Shinehah-Gnolaum** [comment]
The Debug tab doesn't show long enough for me to be able to see it or to lock it in. I can't find in the menu where I can open it. It's not in the Visual Studio Windows menu.

**Comment by jskeet** [comment]
Not the debug tab in output when it's running - it's in the project properties. Right-click on the project in solution explorer, and select "Properties".

**Comment by Shinehah-Gnolaum** [comment]
Ok. I found it. Thanks.

**Comment by jskeet** [comment]
Closing as it looks like this is sorted.

**Comment by Dhanalakshmi-Jayakumar** [comment]
Hi, what context has to be provide in the "Application arguments" textbox

**Comment by jskeet** [comment]
@Dhanalakshmi-Jayakumar: The same arguments that you'd provide on the command line. I would suggest running from the command line to start with, so you can run with the "help" verb etc.

**Comment by Dhanalakshmi-Jayakumar** [comment]
Im not clear with the command line, could you please provide the required details elaborately

**Comment by jskeet** [comment]
It's not clear whether you mean you don't know how to run the code from the command line, or you don't know what command line arguments to supply.
But the README in https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/speech/api gives fairly clear instructions.

If you need more help, please file a new issue explaining what you've tried and exactly what happens.
