### ISSUE TITLE
Error:"invalid_grant", Description:"Robot is disabled."

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [GoogleCloudPlatform/dotnet-docs-samples#844]
When I run Recognize in Visual Studio 2019 on Windows 10 with the following in the project's Properties->Debug->Application arguments:

> async C:\Users\dbrow_000\\source\repos\DotNetConsoleAppSpeechToText01\DotNetConsoleAppSpeechToText01\long.flac

I get an error in the editor in the IDE at the line that starts with var longOperation = ... in the LongRunningRecognize() method, that says:

> Grpc.Core.RpcException: 'Status(StatusCode=Unavailable, Detail="Getting metadata from plugin failed with error: Exception occurred in metadata credentials plugin. Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_grant", Description:"Robot is disabled.", Uri:""
>    at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.ExecuteAsync(TokenRequest request, HttpClient httpClient, String tokenServerUrl, CancellationToken taskCancellationToken, IClock clock) in C:\Apiary\support1351\Src\Support\Google.Apis.Auth\OAuth2\Requests\TokenRequestExtenstions.cs:line 52
>    at Google.Apis.Auth.OAuth2.ServiceAccountCredential.RequestAccessTokenAsync(CancellationToken taskCancellationToken) in C:\Apiary\support1351\Src\Support\Google.Apis.Auth\OAuth2\ServiceAccountCredential.cs:line 212
>    at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync() in C:\Apiary\support1351\Src\Support\Google.Apis.Auth\OAuth2\TokenRefreshManager.cs:line 129
>    at Google.Apis.Auth.OAuth2.TokenRefreshManager.GetAccessTokenForRequestAsync(CancellationToken cancellationToken) in C:\Apiary\support1351\Src\Support\Google.Apis.Auth\OAuth2\TokenRefreshManager.cs:line 114
>    at Google.Apis.Auth.OAuth2.ServiceAccountCredential.GetAccessTokenForRequestAsync(String authUri, CancellationToken cancellationToken) in C:\Apiary\support1351\Src\Support\Google.Apis.Auth\OAuth2\ServiceAccountCredential.cs:line 235
>    at Grpc.Auth.GoogleAuthInterceptors.<>c__DisplayClass2_0.<<FromCredential>b__0>d.MoveNext() in T:\src\github\grpc\src\csharp\Grpc.Auth\GoogleAuthInterceptors.cs:line 48
> --- End of stack trace from previous location where exception was thrown ---
>    at Grpc.Core.Internal.NativeMetadataCredentialsPlugin.GetMetadataAsync(AuthInterceptorContext context, IntPtr callbackPtr, IntPtr userDataPtr) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\NativeMetadataCredentialsPlugin.cs:line 83")'

The primary error as shown above is:

> Error:"invalid_grant", Description:"Robot is disabled."

I've gotten this same error trying code to do a long audio file in other projects.

The Command Line Console doesn't show anything but a blinking caret.

The Output Window doesn't even appear.

**Comment by jskeet** [comment]
Are your credentials by any chance associated with a deleted Google Cloud Project or account? Which credentials are you using?

**Comment by Shinehah-Gnolaum** [comment]
That must be it, because now I get a different error.
