### ISSUE TITLE
Use MySqlConnector in appengine/flexible/CloudSql

### ISSUE THREAD

**Issue by bgrainger** [GoogleCloudPlatform/dotnet-docs-samples#854]
[MySqlConnector](https://github.com/mysql-net/MySqlConnector) is an alternative MySQL client library for .NET with the following advantages:

* fully async, so code like the following will actually execute asynchronously (the current code sample executes synchronously due to a [long-standing bug](https://bugs.mysql.com/bug.php?id=70111) in Connector/NET): https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/3564fd1ddf45133795a37c31362d723752628954/appengine/flexible/CloudSql/Controllers/HomeController.cs#L54
* supports PEM files in the [connection string](https://mysqlconnector.net/connection-options/#ssl-tls-options) so the `openssl` steps at https://cloud.google.com/appengine/docs/flexible/dotnet/using-cloud-sql#configure_ssl_access_to_the_cloud_sql_instance are unnecessary
* [higher performance](https://mysqlconnector.net/#performance), so Google Cloud Platform customers can utilize compute engine instances more efficiently

I'd be happy to open a PR to change the client library from MySql.Data to MySqlConnector (and test the changes) if you'd like: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/3564fd1ddf45133795a37c31362d723752628954/appengine/flexible/CloudSql/CloudSql.csproj#L11

**Comment by amanda-tarafa** [comment]
Hi @bgrainger, thanks. We'll keep using MySql.Data for our samples.
