### ISSUE TITLE
Unable to get data by calling GetSnapshotAsync

### ISSUE THREAD

**Issue by BidyaSagarJena** [GoogleCloudPlatform/dotnet-docs-samples#860]
Hello Team,

The example is working fine in a console application but not working in a windows forms applicaton.

Code
======

        private static void Form1_Load(object sender, EventArgs e)
        {
            string filepath = @"C:\Birghtstar\RnD\DotNet\NotificationTest\SendNotificationTest\SendNotificationTest\Env\jdesimbamonitoring-65815de98a72.json";
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", filepath);

            FirestoreDb db = FirestoreDb.Create(project);
            // [START fs_get_all]
            
            RetrieveAllDocuments("jdesimbamonitoring").Wait();
        }

        private static async Task RetrieveAllDocuments(string project)
        {
            FirestoreDb db = FirestoreDb.Create(project);
            // [START fs_get_all]
            CollectionReference usersRef = db.Collection("Users");
            **QuerySnapshot snapshot = await usersRef.GetSnapshotAsync();**
            foreach (DocumentSnapshot document in snapshot.Documents)
            {
                Console.WriteLine("User: {0}", document.Id);
                Dictionary<string, object> documentDictionary = document.ToDictionary();
                Console.WriteLine("First: {0}", documentDictionary["First"]);
                if (documentDictionary.ContainsKey("Middle"))
                {
                    Console.WriteLine("Middle: {0}", documentDictionary["Middle"]);
                }
                Console.WriteLine("Last: {0}", documentDictionary["Last"]);
                Console.WriteLine("Born: {0}", documentDictionary["Born"]);
                Console.WriteLine();
            }
            // [END fs_get_all]
        }

It stuck in the line QuerySnapshot snapshot = await usersRef.GetSnapshotAsync();
Can you please help me here.

**Comment by jskeet** [comment]
This is the problem:

```csharp
RetrieveAllDocuments("jdesimbamonitoring").Wait();
```

By calling `Wait()`, you're blocking the UI thread - it can't do anything else until the task returned by `RetrieveAllDocuments` has finished.
However, that task can't complete because it needs to come back in the UI thread here:

```csharp
QuerySnapshot snapshot = await usersRef.GetSnapshotAsync();
```

So you've got a deadlock.

The fix is to avoid that `Wait()` call, probably by making your `Form1_Load` method asynchronous and awaiting the task instead. (There are other approaches, but that's probably the simplest:

```csharp
private static async void Form1_Load(object sender, EventArgs e)
{
    string filepath = @"C:\Birghtstar\RnD\DotNet\NotificationTest\SendNotificationTest\SendNotificationTest\Env\jdesimbamonitoring-65815de98a72.json";
    Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", filepath);

    FirestoreDb db = FirestoreDb.Create(project);
    await RetrieveAllDocuments("jdesimbamonitoring");
}
```

That allows the UI thread to await asynchronously - it won't block while the documents are being fetched.

Note that this isn't a Firestore-specific issue - you'd see the same thing in any asynchronous code.

**Comment by jskeet** [comment]
(I'll close this issue now as I'm very confident that's the problem. Please add a comment if this doesn't work for you and you need the issue to be reopened.)
