### ISSUE TITLE
Pub/Sub: publish example doesn't seem to publish anything

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/dotnet-docs-samples#861]
Could we update this sample to match existing publish examples in other languages [here](https://cloud.google.com/pubsub/docs/publisher#publish), specifically Python/Java/Go? The goal is to show publish *multiple* messages *with error-handling*. 

https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/04a4b67baa05a84ad85ed0904a7af4acfa6a106f/pubsub/api/PubsubSample/Program.cs#L243-L246

**Comment by amanda-tarafa** [comment]
@SurferJeffAtGoogle assigning to you since you are the last person to have modified the offending sample.

**Comment by amanda-tarafa** [comment]
Actually, I can do this now.

**Comment by meredithslota** [comment]
Yay! This issue is OOSLO and I was just about try to find an owner, and here you are. :) Thank you!

**Comment by amanda-tarafa** [comment]
I'll get to it this week!
