### ISSUE TITLE
WordTimeOffsets gets reset after creating new StreamingRecognizeRequest(need InfiniteStreamRecognize in c#)

### ISSUE THREAD

**Issue by phanser83** [GoogleCloudPlatform/dotnet-docs-samples#864]
Hi,
I am trying to get transcription along with its word info specially for start and end timings for each and every word. This is for long streaming videos for which audio is extracted using ffmpeg. when it reaches 5 mins of video it throws error about maximum allowed stream length.
To Avoid "Exceeded maximum allowed stream duration of 305 seconds " error, I am creating new StreamingRecognizeRequest. In which case some chunks of bytes are getting lost. And also main feature of wordtimeoffset gets reset on new request. which is not useful.
so whenever I send new request after 5 mins of audio response stream gives start time of the word from new request as 0.003 s etc.. where as it should be 5.12 s something similar.
For example ,
"0.300s" --> "12.300s" My first time in the studio when she got this is the first topic that I'm doing a video on because it's an important topic. So where we get today to talk about the gender pay and broadly about diversity.
"0.500s" --> "13.400s" And it and it did it security key topic that year ago. We started having a more formal conversation about giving the gender pay Gap reporting and it's been a year of a lot of activity and so it says something like this.
line "And it and it did it security key topic. " shows start time with new start time 0.500 secs. where as it should have been continue with 12.300s + seconds. where broadly about diversity.. statement ends. but as I said it is new request send to api . api thinks it is new audio received. where as Audio is same , it is only send in chunks of byte in a loop.
Can anyone here help me to understand workaround to this ?
Thanks,
RP

**Comment by jskeet** [comment]
Trying to break the stream into chunks will indeed cause difficulties. I suggest you try to use the "infinite streaming" approach shown [here](https://cloud.google.com/speech-to-text/docs/streaming-tutorial). There isn't a C# example yet, but I'm hoping we'll have one in a few weeks.

**Comment by phanser83** [comment]
Hi , Thanks for your reply. I missed it as i was not subscribed for notification. There is sample available  now in c# for infinite streaming. I will have a look at that. I did refer java infinite streaming code but java code has some issues (i run in maven, eclipse) in getting endresulttime correct after sending new request. Same issue occur in my c# code (i wrote myself referring to java code). I will let you know if i can use c# infinite streaming code. As that code is for mic recognition only and not for audio from  file or Stream. 

Thanks,
RP

**Comment by amanda-tarafa** [comment]
@phanser83 Did you manage to get your issues solved by looking at the C# infinite streaming sample?

**Comment by amanda-tarafa** [comment]
@phanser83 Closing this issue for now. If you are still experiencing problems, leave a comment and we can reopen. Thanks.
