### ISSUE TITLE
System.AggregateException error on FirestoreDb

### ISSUE THREAD

**Issue by voliverio** [GoogleCloudPlatform/dotnet-docs-samples#877]
Hi,

I have an ASP.Net project using Google.Cloud.Firestore API to connect to a Firestore database but I can't get it to work. When I try to query data or add data I get an System.AggregateException saying "The entry point was not found".

Here follows the code I'm using:

`
string filepath = @"<file_path";
Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", filepath);
string projectId = "project-id";

FirestoreDb firestoreDB = FirestoreDb.Create(projectId);
CollectionReference collectionReference = firestoreDB.Collection("AcaoEquipamento");

// A CollectionReference is a Query, so we can just fetch everything
QuerySnapshot allCities = collectionReference.GetSnapshotAsync().Result;
foreach (DocumentSnapshot document in allCities.Documents)
{
          Console.WriteLine(document.Id);
}
`

Does anyone knows what am I doing wrong?

Thank you.

**Comment by jskeet** [comment]
Please could you show the complete stack trace, and specify the exact version of the Firestore package you're using?

**Comment by jskeet** [comment]
I'd expect to see more than that in the stack trace - and it's odd that that's coming up when disposing. Please could you provide the platform versions mentioned in my earlier comment? If you could give me a complete recipe to reproduce the problem, that would help a lot.

**Comment by jskeet** [comment]
I'll try to reproduce it tomorrow. I'd expect it to be okay... (I'm not sure if I've still got VS2017 installed, but I'll try on VS2019 first.)

I don't think this will be an authentication issue.

**Comment by jskeet** [comment]
Can I ask if you're connected with user bjornbacklund, who reported https://github.com/googleapis/google-cloud-dotnet/issues/3398 yesterday? It seems unusual for the same issue to be reported twice within a few hours if they're unconnected.
If you work on the same project, I suggest I close this issue and you subscribe to the other one.

**Comment by voliverio** [comment]
Hi Jon,

Actually it is a coincidence, I don't know him.

Thank you.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by jskeet** [comment]
Gosh, interesting.

Anyway, I suspect the cause is the same: I suspect you've got a dependency on Grpc.Core 2.23.0, which is incompatible with the Firestore library. I'm going to try to update our GAX libraries to add an upper bound to the Grpc.Core dependency, so that this causes a build-time error.
(We'll be updating to the new version of Grpc.Core at some point, but that will cause a major version bump in all libraries.)

Please check this, and if that's *not* the case, please list all your dependencies including their versions - I'm sure the problem is in there somewhere.

**Comment by voliverio** [comment]
Hi Jon,

That was the problem, I downgraded Grpc to 1.22 as you suggested in [https://github.com/googleapis/google-cloud-dotnet/issues/3398](url) and it worked.

Thank you very much.
