### ISSUE TITLE
Dialogflow.DetectIntentTextsTest not passing

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#935]
The test defined in [DetectIntentTextsTest.TestDetectIntentFromTexts](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/dialogflow/api/Test/DetectIntentTextsTest.cs is not passing, it seems to be very strict. It's OK to loosen it up, we just want to test that the sample makese sense.
It should be checked by someone who is familiar with the Dialogflow API and can write a good enough test.

**Comment by amanda-tarafa** [comment]
@telpirion I've assigned this to you because I know you have been working on some of the Dialogflow samples, but please feel free to assign to someone who might be familiar with the Dialogflow API.
I think the test is too strict and can be loosen up so that it passes, but I'm not that familiar with the Dialogflow API as to know what is a good enough test.
Wait till #936 is merged to start on this so you can benefit from the fixes there.

**Comment by telpirion** [comment]
@nnegrey Who is much more knowledgeable about Dialogflow than I am.

I'll take a look this week and try to diagnose what the issue is.
