### ISSUE TITLE
Any Memorystore Redis example

### ISSUE THREAD

**Issue by mitulpanch** [GoogleCloudPlatform/dotnet-docs-samples#944]
Would really appreciate an example of Memorystore Redis for .net core

**Comment by amanda-tarafa** [comment]
I'll try to have some examples include. In the meantime, there's some basic information and the library reference here: https://googleapis.dev/dotnet/Google.Cloud.Redis.V1/latest/index.html

**Comment by laljikanjareeya** [comment]
@amanda-tarafa currently, I am working on same, will create PR shortly.

**Comment by amanda-tarafa** [comment]
Oh that's great @laljikanjareeya. I'll assing the issue to you then, thanks!.

**Comment by amanda-tarafa** [comment]
@mitulpanch Unfortunately we currently don't have the bandwidth to maintain and publish these samples so I'll be closing this issue for now. It will stay on our backlog and will be considered for the future.
In the meantime [here](https://googleapis.dev/dotnet/Google.Cloud.Memcache.V1Beta2/1.0.0-beta02/index.html)'s some documentation that should help with getting started.
And here the [client library reference documentation](https://googleapis.dev/dotnet/Google.Cloud.Memcache.V1Beta2/1.0.0-beta02/api/Google.Cloud.Memcache.V1Beta2.html).

**Comment by idofl** [comment]
If you are looking for an example that shows how to access a Memorystore Redis instance from .NET Core, see here:
https://github.com/idofl/dotnet-memorystore-redis
