### ISSUE TITLE
Update Google Home meets .NET Containers dependencies.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/dotnet-docs-samples#987]
We have taken a [major version bump on all client libraries](https://github.com/googleapis/google-cloud-dotnet/blob/master/docs/root/major-version.md) and it would be nice if [this application](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/tree/master/applications/googlehome-meets-dotnetcontainers)'s dependencies were updated.
@meteatamel assigning to you since you created the application. I've updated and checked almost everything else in this repo, but this being a demo doesn't have any tests, so I didn't want to change it myself without being able to checked if it was still working.
Also, if this is now outdated or irrelevant, it's fine to just remove it from the repo.

**Comment by meteatamel** [comment]
Hi Amanda, I checked and the dependencies are already automatically updated. I setup and ran the sample and it still works, so I think we're good. I had to change the Dockerfile a little to get the sample working, and sent a pull request to have that change in the main repo. Please merge.

**Comment by amanda-tarafa** [comment]
Thanks! Will merge shortly.

**Comment by amanda-tarafa** [comment]
Closed via #989
